////

|metadata|
{
    "name": "configuring-and-retrieving-input-masks-dynamically",
    "controlName": ["WebMaskEditor"],
    "tags": ["API","Editing","How Do I","Tips and Tricks"],
    "guid": "2d4d1573-a2c8-4348-9ed4-7c965fb53b57",  
    "buildFlags": [],
    "createdOn": "2012-09-19T11:52:32.7431832Z"
}
|metadata|
////

= Configuring And Retrieving Input Masks Dynamically

== Topic Overview

=== Purpose

This topic demonstrates how to get and set the  _WebMaskEdito_  r™ input masks dynamically.

=== Required background

The following topics are prerequisites to understanding this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:webmaskeditor-about-webmaskeditor.html[About WebMaskEditor]
|This topic introduces the _WebMaskEditor_ control and its features.

| link:webmaskeditor-overview-of-masks.html[Masks Overview]
|This topic demonstrates the meaning of the symbols that you need in order to create _WebMaskEditor_ mask.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref326941850,WebMaskEditor Input Masks Summary>>
* <<_Ref326941854,Get and Set the WebMaskEditor Input Masks on the Server>>

* <<_Ref326941857,Example for Setting Mask>>
* <<_Ref326941870,Example for Getting Mask>>

* <<_Ref326941874,Get and Set WebMaskEditor Input Masks on the Client>>

* <<_Ref326941877,Example for Setting Mask>>
* <<_Ref326941879,Example for Getting Mask>>

* <<_Ref326941886,Related Content>>

* <<_Ref326941914,Topics>>
* <<_Ref326941917,Samples>>

[[_Ref326941850]]
== Configuring Input Masks Summary

=== Configuring Input Masks summary chart

The following table lists the configurable aspects of the  _WebMaskEditor_   control:

[options="header", cols="a,a,a"]
|====
|Configurable aspects|Details|Properties and Methods

|1 .Set the _WebMaskEditor_ mask on Server-side 

2*.* Get the WebMaskEditor mask on Server-side
|The InputMask property is the one that needs to be used for setting and getting the _WebMaskEditor_ ’s masks.
|
* link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webmaskeditor~inputmask.html[InputMask] 

|1 .Set the _WebMaskEditor_ mask on Client-side 

2*.* Get the _WebMaskEditor_ mask on Client-side
|__The__ _WebMaskEditor_ exposes two client-side methods for setting and getting the _WebMaskEditor_ masks.
|
* link:webtexteditor~infragistics.web.ui.webmaskeditor~inputmask.html[set_inputMask()] 

* link:webtexteditor~infragistics.web.ui.webmaskeditor~inputmask.html[get_inputMask()] 

|====

[[_Ref326941854]]
== Get and Set  _WebMaskEditor_   the Input Masks on the Server

=== Overview

In order to get or set the  _WebMaskEditor_   mask on the server, you simply need to get or set the control property called ` link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webmaskeditor~inputmask.html[InputMask]`.

[[_Ref326941857]]

=== Example for Setting Mask

The code below demonstrates how to set the  _WebMaskEditor_   input mask on the server using the markup or code-behind:

*In ASPX:*

[source,html]
----
<ig:WebMaskEditor ID="WebMaskEditor1” runat="server"
InputMask="###-##-####"/>
----

*In C#:*

[source,csharp]
----
this.WebMaskEditor1.InputMask = "###-##-####";
----

[[_Ref326941870]]

=== Example for Getting Mask

The code below demonstrates how to get the  _WebMaskEditor_   input mask on the server:

*In C#:*

[source,csharp]
----
string inputMask = this.phoneEditor.InputMask;
----

[[_Ref326941874]]
== Get and Set  _WebMaskEditor_   Input Masks on the Client

=== Overview

The  _WebMaskEditor_   client-side object model proposes two methods for getting and setting the input mask. They are ` link:webtexteditor~infragistics.web.ui.webmaskeditor~inputmask.html[get_inputMask()]` and ` link:webtexteditor~infragistics.web.ui.webmaskeditor~inputmask.html[set_inputMask()]`. In a scenario when you need to change the mask dynamically, this will save you from having to make a request to the server in order to configure the  _WebMaskEditor_  .

[[_Ref326941877]]

=== Example for Setting Mask

The code below demonstrates how the ` link:webtexteditor~infragistics.web.ui.webmaskeditor~inputmask.html[set_inputMask()]` method is used to set the  _WebMaskEditor_   input mask dynamically on the client:

*In JavaScript:*

[source,js]
----
$find("<%= this.WebMaskEditor1.ClientID %>").set_inputMask(“###-##-####”);
----

[[_Ref326941879]]

=== Example for Getting Mask

The code below demonstrates how the ` link:webtexteditor~infragistics.web.ui.webmaskeditor~inputmask.html[get_inputMask()]` method is used to get the  _WebMaskEditor_   input mask dynamically on the client:

*In JavaScript:*

[source,js]
----
var mask = $find("<%= this.WebMaskEditor1.ClientID %>").get_inputMask();
----

[[_Ref326941886]]
== Related Content

[[_Ref326941914]]

=== Topics

The following topics provide additional information related to this topic:

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:webmaskeditor-about-webmaskeditor.html[About WebMaskEditor]
|This topic introduces the _WebMaskEditor_ control and its features.

| link:webmaskeditor-overview-of-masks.html[Masks Overview]
|This topic demonstrates the meaning of the symbols that you need to create _WebMaskEditor_ mask.

|====

[[_Ref326941917]]

=== Samples

The following samples provide additional information related to this topic:

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesUrl}/editors/mask-editor-client-side-input-mask[Mask Editor Client-Side Input Mask]
|This sample demonstrates how to dynamically change the input mask of WebMaskEditor control using its client API.

|====