////

|metadata|
{
    "name": "persistenceframework-api-overview",
    "controlName": ["PersistenceFramework"],
    "tags": ["API","Persistence"],
    "guid": "89304c00-e244-4f7a-ba0c-57f65f12cf2e",  
    "buildFlags": [],
    "createdOn": "2011-05-31T14:41:06.2907675Z"
}
|metadata|
////

= API Overview

This section lists each namespace that is relevant to the framework. We also give you several key classes that you will be using while programming with this framework. The namespaces and classes on this page link directly into our API documentation.

=== PersistenceFramework Namespace:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence_namespace.html[Infragistics.Web.UI.Framework.Persistence]"]

=== Key Classes:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.apppersistencemanager.html[AppPersistenceManager]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.controldata.html[ControlData]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.persistencedata.html[PersistenceData]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.persistencemanager.html[PersistenceManager]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.propertydata.html[PropertyData]"]