////

|metadata|
{
    "name": "waw-infragistics-excel-engine",
    "controlName": [],
    "tags": ["Data Presentation","Exporting","Grids"],
    "guid": "{8264A2E4-40BE-4A90-9B8D-1C95477AADE5}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Infragistics Excel Engine

If you’re looking for an area that houses all of the overview/task-based information related to the Infragistics Excel Engine™, you've come to the right place. This section contains valuable information about the Infragistics Excel Engine, ranging from what the code library does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the code library.

Click the links below to access important information about the Infragistics Excel Engine.

== link:excelengine-understanding-the-infragistics-excel-engine.html[Understanding the Infragistics Excel Engine]

In this section you’ll find any information that will help you to better understand the functionalities of the Infragistics Excel Engine, as well as why you would want to use it as part of building your applications.

== link:excelengine-using-the-infragistics-excel-engine.html[Using the Infragistics Excel Engine]

This section contains detailed, step-by-step procedures that guide you through common scenarios that you may need to perform when using the Infragistics Excel Engine.

== link:excelengine-deploying-the-infragistics-excel-engine.html[Deploying the Infragistics Excel Engine]

If your application uses the Infragistics Excel Engine, refer to this topic for a list of the Infragistics .NET assemblies that you need to redistribute as part of your application.

== link:excelengine-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the Infragistics Excel Engine. The namespaces and classes listed in this topic link conveniently into the "API Reference Guide" section of the Infragistics ASP.NET help.