////

|metadata|
{
    "name": "web-webmaskeditor",
    "controlName": ["WebMaskEditor"],
    "tags": [],
    "guid": "{E2C962F7-F7B5-41F0-BB23-10F26F211858}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T14:37:45Z"
}
|metadata|
////

= WebMaskEditor

This page contains all of the overview/task-based information related to the WebMaskEditor™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebMaskEditor control.

== link:webmaskeditor-about-webmaskeditor.html[About WebMaskEditor]

In this section, you will find information that will help you better understand functionalities of the WebMaskEditor control. Further,you will understand the purpose of the control.

== link:webmaskeditor-using-webmaskeditor.html[Using WebMaskEditor]

This section provides task-based information showing you how to use the features available in WebMaskEditor.

== link:webmaskeditor-accessibility-compliance.html[WebMaskEditor Accessibility Compliance]

This topic outlines the way in which WebMaskEditor meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebMaskEditor control.

== link:webmaskeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebMaskEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtexteditor~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebMaskEditor™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.