////

|metadata|
{
    "name": "web-webprogressbar",
    "controlName": ["WebProgressBar"],
    "tags": [],
    "guid": "{12452F2F-54BC-4FEE-B3E2-A97874FD03EF}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebProgressBar

This page contains all of the overview/task-based information related to the WebProgressBar™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebProgressBar control.

== link:webprogressbar-about-webprogressbar.html[About WebProgressBar]

In this section, you will find information that will help you better understand functionalities of the WebProgressBar control. Further, you will understand the purpose of the control.

== link:webprogressbar-getting-started-with-webprogressbar.html[Getting Started with WebProgressBar]

This section provides you with information on how to get up and running as quickly as possible with the WebProgressBar control.

== link:webprogressbar-using-webprogressbar.html[Using WebProgressBar]

This section provides task-based information showing you how to use the features available in WebProgressBar.

== link:webprogressbar-accessibility-compliance.html[WebProgressBar Accessibility Compliance]

This topic outlines the way in which WebProgressBar meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebProgressBar control.

== link:webprogressbar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebProgressBar control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webprogressbar~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebProgressBar™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.