////

|metadata|
{
    "name": "web-webdropdown",
    "controlName": ["WebDropDown"],
    "tags": ["Getting Started"],
    "guid": "{65E75279-3178-43D0-AF19-31212E991692}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDropDown

This page contains all of the overview/task-based information related to the WebDropDown™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebDropDown control.

== link:webdropdown-about-webdropdown.html[About WebDropDown]

In this section, you will find information that will help you better understand functionalities of the WebDropDown control. Further,you will understand the purpose of the control.

== link:webdropdown-getting-started-with-webdropdown.html[Getting Started with WebDropDown]

This section provides you with information on how to get up and running as quickly as possible with the WebDropDown control.

== link:webdropdown-using-webdropdown.html[Using WebDropDown]

This section provides task-based information showing you how to use the features available in WebDropDown.

== link:webdropdown-accessibility-compliance.html[WebDropDown Accessibility Compliance]

This topic outlines the way in which WebDropDown meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebDropDown control.

== link:webdropdown-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebDropDown control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webdropdown~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebDropDown™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.