////

|metadata|
{
    "name": "web-webschedulesqlclientprovider",
    "controlName": ["WebScheduleSqlProvider"],
    "tags": ["Data Presentation","Persistence","Sample Data Source"],
    "guid": "{28F1135A-47E4-4CF0-BA7D-7040062AA546}",  
    "buildFlags": [],
    "createdOn": "2005-07-12T00:00:00Z"
}
|metadata|
////

= WebScheduleSqlClientProvider

Click the links below for an introduction to the WebScheduleSqlClientProvider™ component.

* link:webschedulesqlclientprovider-about-webschedulesqlclientprovider.html[About WebScheduleSqlClientProvider] -- Provides information on what the WebScheduleSqlProvider component does, and why you would want to use it in your application.
* link:webschedulesqlclientprovider-smart-tag.html[WebScheduleSqlClientProvider Smart Tag] -- Explains the functionality available on the WebScheduleSqlClientProvider smart tag.

The WebScheduleSqlClientProvider component is part of the WebSchedule™ group of controls and components. If you're looking for a section that houses overview/task-based information common to multiple WebSchedule controls and components (e.g., WebCalendarView™, ScheduleOleDbProvider™), click the link below:

link:web-webschedule.html[WebSchedule]