////

|metadata|
{
    "name": "web-webimageviewer",
    "controlName": ["WebImageViewer"],
    "tags": [],
    "guid": "{9009ABD7-E514-48E4-B648-CCEC8513CC02}",  
    "buildFlags": [],
    "createdOn": "2008-12-01T20:41:05Z"
}
|metadata|
////

= WebImageViewer

If you're looking for an area that houses all of the overview/task-based information related to the WebImageViewer™ control, you've come to the right place. This section contains valuable information about WebImageViewer, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WebImageViewer control.

== link:webimageviewer-about-webimageviewer.html[About WebImageViewer]

In this section you'll find any information that will help you to better understand the functionalities of the WebImageViewer control, as well as why you would want to use it to as part of building your applications.

== link:webimageviewer-getting-started-with-the-webimageviewer.html[Getting Started with WebImageViewer]

In order to get you up and running as quickly as possible with the WebImageViewer control, we've provided you with information on how to get started using the control (i.e., adding WebImageViewer to a form).

== link:webimageviewer-using-webimageviewer.html[Using WebImageViewer]

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the WebImageViewer control.

== link:webimageviewer-webimageviewer-accessibility-compliance.html[WebImageViewer Accessibility Compliance]

This topic outlines the way in which WebImageViewer meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebImageViewer control.

== link:webimageviewer-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebImageViewer control. The namespaces and classes listed in this topic link conveniently into the link:web-api-reference-guide.html[API Reference Guide] section of the Infragistics ASP.NET help.

== link:webimageviewer~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebImageViewer™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the image viewer without the need for server-side post-backs.