////

|metadata|
{
    "name": "web-webmonthcalendar",
    "controlName": ["WebMonthCalendar"],
    "tags": [],
    "guid": "{127F60EF-2DC8-4D15-AD4E-A36A4FD63F62}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebMonthCalendar

This page contains all of the overview/task-based information related to the WebMonthCalendar™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebMonthCalendar control.

== link:webmonthcalendar-about-webmonthcalendar.html[About WebMonthCalendar]

In this section, you will find information that will help you better understand functionalities of the WebMonthCalendar control. Further,you will understand the purpose of the control.

== link:webmonthcalendar-getting-started-with-webmonthcalendar.html[Getting Started with WebMonthCalendar]

This section provides you with information on how to get up and running as quickly as possible with the WebMonthCalendar control.

== link:webmonthcalendar-using-webmonthcalendar.html[Using WebMonthCalendar]

This section provides task-based information showing you how to use the features available in WebMonthCalendar.

== link:webmonthcalendar-accessibility-compliance.html[WebMonthCalendar Accessibility Compliance]

This topic outlines the way in which WebMonthCalendar meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebMonthCalendar control.

== link:webmonthcalendar-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebMonthCalendar control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webmonthcalendar~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebMonthCalendar™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.