////

|metadata|
{
    "name": "web-webcaptcha",
    "controlName": ["WebCaptcha"],
    "tags": ["Getting Started"],
    "guid": "43556d83-fed2-4e43-a122-55b0232ae670",  
    "buildFlags": [],
    "createdOn": "2010-05-31T10:58:26.797816Z"
}
|metadata|
////

= WebCaptcha

This page contains all of the overview/task-based information related to the WebCaptcha™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebCaptcha control.

== link:webcaptcha-about-webcaptcha.html[About WebCaptcha]

In this section, you will find information that will help you better understand functionalities of the WebCaptcha control. Further, you will understand the purpose of the control.

== link:webcaptcha-getting-started-with-webcaptcha.html[Getting Started with WebCaptcha]

This section provides you with information on how to get up and running as quickly as possible with the WebCaptcha control.

== link:webcaptcha-using-webcaptcha.html[Using WebCaptcha]

This section provides task-based information showing you how to use the features available in WebCaptcha.

== link:webcaptcha-accessibility-compliance-.html[WebCaptcha Accessibility Compliance]

This topic outlines the way in which WebCaptcha meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebCaptcha control.

== link:webcaptcha-api-overvew.html[API Overvew]

This topic lists the namespaces and classes that you will be working with while programming with the WebCaptcha control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webcaptcha~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebCaptcha control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.