////

|metadata|
{
    "name": "web-webrating",
    "controlName": ["WebRating"],
    "tags": ["Getting Started"],
    "guid": "871073ab-c989-4636-b275-65d62ad07e0e",  
    "buildFlags": [],
    "createdOn": "2010-06-01T04:42:24.7126693Z"
}
|metadata|
////

= WebRating

This page contains all of the overview/task-based information related to the WebRating™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebRating control.

== link:webrating-about-webrating.html[About WebRating]

In this section, you will find information that will help you better understand functionalities of the WebRating control. Further, you will understand the purpose of the control.

== link:webrating-getting-started-with-webrating.html[Getting Started with WebRating]

This section provides you with information on how to get up and running as quickly as possible with the WebRating control.

== link:webrating-using-webrating.html[Using WebRating]

This section provides task-based information showing you how to use the features available in WebRating.

== link:webrating-accessibility-compliance.html[WebRating Accessibility Compliance]

This topic outlines the way in which WebRating meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebRating control.

== link:webrating-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebRating control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webrating~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebRating™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.