////

|metadata|
{
    "name": "web-webtab",
    "controlName": ["WebTab"],
    "tags": ["Layouts"],
    "guid": "{84E62C34-C90E-4F95-90AF-FAD6909A4434}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebTab

This page contains all of the overview/task-based information related to the WebTab™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebTab control.

== link:webtab-about-webtab.html[About WebTab]

In this section, you will find information that will help you better understand functionalities of the WebTab control. Further, you will understand the purpose of the control.

== link:webtab-getting-started-with-webtab.html[Getting Started with WebTab]

This section provides you with information on how to get up and running as quickly as possible with the WebTab control.

== link:webtab-using-webtab.html[Using WebTab]

This section provides task-based information showing you how to use the features available in WebTab.

== link:webtab-accessibility-compliance.html[WebTab Accessibility Compliance]

This topic outlines the way in which WebTab meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebTab control.

== link:webtab-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebTab control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtab~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebTab™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.