////

|metadata|
{
    "name": "web-webtexteditor",
    "controlName": ["WebTextEditor"],
    "tags": [],
    "guid": "{1FE8CD62-269A-4B47-B848-97018D23A082}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebTextEditor

This page contains all of the overview/task-based information related to the WebTextEditor™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebTextEditor control.

== link:webtexteditor-about-webtexteditor.html[About WebTextEditor]

In this section, you will find information that will help you better understand functionalities of the WebTextEditor control. Further, you will understand the purpose of the control.

== link:webtexteditor-using-webtexteditor.html[Using WebTextEditor]

This section provides task-based information showing you how to use the features available in WebTextEditor.

== link:webtexteditor-accessibility-compliance.html[WebTextEditor Accessibility Compliance]

This topic outlines the way in which WebTextEditor meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebTextEditor control.

== link:webtexteditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebTextEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtexteditor~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebTextEditor™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.