////

|metadata|
{
    "name": "web-webslider",
    "controlName": ["WebSlider"],
    "tags": [],
    "guid": "{4B2D66B3-F45E-4182-8843-C60A1E39C4F4}",  
    "buildFlags": [],
    "createdOn": "2008-08-05T16:24:15Z"
}
|metadata|
////

= WebSlider

This page contains all of the overview/task-based information related to the WebSlider™ control. This section contains valuable information about WebSlider, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WebSlider control.

== link:webslider-about-webslider.html[About WebSlider]

In this section you'll find any information that will help you to better understand the functionalities of the WebSlider control, as well as why you would want to use it to as part of building your applications.

== link:webslider-getting-started-with-webslider.html[Getting Started with WebSlider]

In order to get you up and running as quickly as possible with the WebSlider control, we've provided you with information on how to get started using the control.

== link:webslider-using-webslider.html[Using WebSlider]

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the WebSlider control.

== link:webslider-accessibility-compliance.html[WebSlider Accessibility Compliance]

This topic outlines the way in which WebSlider meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebSlider control.

== link:webslider-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebSlider control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webslider~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebSlider™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the image viewer without the need for server-side post-backs.