////

|metadata|
{
    "name": "web-deploying-an-application-to-a-partial-trust-environment",
    "controlName": [],
    "tags": ["Deployment","How Do I"],
    "guid": "{DD70F459-BA1F-4CD5-82B8-48BBFE475BF4}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Deploying an Application to a Partial-Trust Environment

Starting in the 2006 Volume 3 release, the Infragistics ASP.NET product provides a set of assemblies marked with Microsoft® .NET Framework's AllowPartiallyTrustedcallersAttribute (APTCA) attribute. These specially-marked assemblies are capable of running in a partially trusted environment.

The procedure for deploying APTCA assemblies is the same as the procedure for deploying non-APTCA (release) assemblies. At deployment time, you need to copy (or FTP) the APTCA assemblies to the Bin folder of your Web application on your Web server in the same way as you would deploy the assemblies of your Web application.

You can make the deployment independent of the build number of the assemblies by specifying a <bindingRedirect> in your Web application's web.config file. This technique helps to avoid having to update any @Register directives in the ASPX pages if the @Register directives differ from the version/build number of the assemblies being deployed.

To deploy your Web application to a partial-trust environment:

For each Infragistics assembly referenced by your Web application, place the following two elements in the <runtime>, <assemblyBindings> and <dependentAssembly> sections of your web.config file.

* <assemblyIdentity> -- Specify this element for each <dependentAssembly> element, and it contains the assembly file name (without the ".dll" file extension) and public key token ("7dd5c3163f2cd0cb" for all Infragistics assemblies).
* <bindingRedirect> -- This element contains one or more old version/build numbers that need to be mapped to a new version/build number. You may need to add thse elements if they were not already present in your web.config file by default.

The following example illustrates how to use a binding redirect on the Infragistics.WebUI.Shared and Infragistics.Excel assemblies.

[source]
----
</
----

[source]
----
system.web
----

[source]
----
>
----

[source]
----
<
----

[source]
----
runtime
----

[source]
----
>
----

[source]
----
<
----

[source]
----
assemblyBinding
----

[source]
----
xmlns="urn:schemas-microsoft-com:asm.vl"
----

[source]
----
>
----

[source]
----
<
----

[source]
----
dependentAssembly
----

[source]
----
>
----

[source]
----
<
----

[source]
----
assemblyIdentity
----

[source]
----
name="
----

[source]
----
Infragistics.WebUI.Shared.v8.1
----

[source]
----
"
----

[source]
----
publicKeyToken="
----

[source]
----
7dd5c3163f2cd0cb
----

[source]
----
"/>
----

[source]
----
<
----

[source]
----
bindingRedirect
----

[source]
----
oldVersion="
----

[source]
----
8.1.20081.1-8.1.20081.1050
----

[source]
----
"
----

[source]
----
newVersion="
----

[source]
----
8.1.20081.1050
----

[source]
----
"
----

[source]
----
/>
----

[source]
----
</
----

[source]
----
dependentAssembly
----

[source]
----
>
----

[source]
----
<
----

[source]
----
dependentAssembly
----

[source]
----
>
----

[source]
----
<
----

[source]
----
assemblyIdentity
----

[source]
----
name="
----

[source]
----
Infragistics.Excel.v8.1
----

[source]
----
"
----

[source]
----
publicKeyToken="
----

[source]
----
7dd5c3163f2cd0cb
----

[source]
----
"
----

[source]
----
/>
----

[source]
----
<
----

[source]
----
bindingRedirect
----

[source]
----
oldVersion="
----

[source]
----
8.1.20081.1-8.1.20081.1050
----

[source]
----
"
----

[source]
----
newVersion="
----

[source]
----
8.1.20081.1050
----

[source]
----
"
----

[source]
----
/>
----

[source]
----
</
----

[source]
----
dependentAssembly
----

[source]
----
>
----

[source]
----
...
----

[source]
----
</
----

[source]
----
assemblyBinding
----

[source]
----
>
----

[source]
----
</
----

[source]
----
runtime
----

[source]
----
>
----

[source]
----
</
----

[source]
----
configuration
----

[source]
----
>
----

These <bindingRedirect> declarations inform the .NET Framework runtime to load the assemblies located in your Bin folder (which can have any build number within the range specified by the oldVersion attribute) and treat them as if they had the build number specified by the newVersion attribute. Using <bindingReditrect> in this way helps to ensure a seamless deployment, even if the build number of the assemblies on your Web site differs from those used on your development machine.

== Related Topic

link:web-asp-net-aptca-assemblies.html[ASP.NET APTCA Assemblies]