////

|metadata|
{
    "name": "web-webdatetimeeditor",
    "controlName": ["WebDateTimeEditor"],
    "tags": [],
    "guid": "{E8E656D6-AAD2-4B53-B46B-05443E7A49D4}",  
    "buildFlags": [],
    "createdOn": "2009-04-06T17:00:19Z"
}
|metadata|
////

= WebDateTimeEditor

This page contains all of the overview/task-based information related to the WebDateTimeEditor™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebDateTimeEditor control.

== link:webdatetimeeditor-about-webdatetimeeditor.html[About WebDateTimeEditor]

In this section, you will find information that will help you better understand functionalities of the WebDateTimeEditor control. Further,you will understand the purpose of the control.

== link:webdatetimeeditor-using-webdatetimeeditor.html[Using WebDateTimeEditor]

This section provides task-based information showing you how to use the features available in WebDateTimeEditor.

== link:webdatetimeeditor-accessibility-compliance.html[WebDateTimeEditor Accessibility Compliance]

This topic outlines the way in which WebDateTimeEditor meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebDateTimeEditor control.

== link:webdatetimeeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebDateTimeEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtexteditor~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebDateTimeEditor™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.