////

|metadata|
{
    "name": "web-webscheduleoledbprovider",
    "controlName": ["WebScheduleOleProvider"],
    "tags": ["Data Presentation","Persistence","Sample Data Source"],
    "guid": "{EDF6F57F-3071-477D-9F5A-2974A1A5C863}",  
    "buildFlags": [],
    "createdOn": "2005-07-12T00:00:00Z"
}
|metadata|
////

= WebScheduleOleDbProvider

Click the links below for an introduction to the WebScheduleOleDbProvider™ component.

* link:webscheduleoledbprovider-about-webscheduleoledbprovider.html[About WebScheduleOleDbProvider] -- Provides information on what the WebScheduleOleProvider component does, and why you would want to use it in your application.
* link:webscheduleoledbprovider-smart-tag.html[WebScheduleOleDbProvider Smart Tag] -- Explains the functionality available on the WebScheduleOleDbProvider smart tag.

The WebScheduleOleDbProvider component is part of the WebSchedule™ group of controls and components. If you're looking for a section that houses overview/task-based information common to multiple WebSchedule controls and components (e.g., WebCalendarView™, ScheduleSqlClientProvider™), click the link below:

link:web-webschedule.html[WebSchedule]