////

|metadata|
{
    "name": "web-webhierarchicaldatasource",
    "controlName": ["WebHierarchicalDataSource"],
    "tags": [],
    "guid": "{55CE966B-7CF7-48E8-8CC3-2F1C67E517FB}",  
    "buildFlags": [],
    "createdOn": "2008-02-05T11:18:01Z"
}
|metadata|
////

= WebHierarchicalDataSource

This page contains all of the overview/task-based information related to the WebHierarchicalDataSource™ control. This section contains valuable information about WebHierarchicalDataSource, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WebHierarchicalDataSource control.

== link:webhierarchicaldatasource-about-webhierarchicaldatasource.html[About WebHierarchicalDataSource]

In this section you'll find any information that will help you to better understand the functionalities of the WebHierarchicalDataSource control, as well as why you would want to use it to as part of building your applications.

== link:webhierarchicaldatasource-getting-started-with-webhierarchicaldatasource.html[Getting Started with WebHierarchicalDataSource]

In order to get you up and running as quickly as possible with the WebHierarchicalDataSource control, we've provided you with information on how to get started using the control.

== link:webhierarchicaldatasource-using-webhierarchicaldatasource.html[Using WebHierarchicalDataSource]

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the WebHierarchicalDataSource control.

== link:webhierarchicaldatasource-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebHierarchicalDataSource control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.