////

|metadata|
{
    "name": "web-webcurrencyeditor",
    "controlName": ["WebCurrencyEditor"],
    "tags": [],
    "guid": "{B444FF54-16BB-476D-87B2-30DDAA11F782}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:23:22Z"
}
|metadata|
////

= WebCurrencyEditor

This page contains all of the overview/task-based information related to the WebCurrencyEditor™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebCurrencyEditor control.

== link:webcurrencyeditor-about-webcurrencyeditor.html[About WebCurrencyEditor]

In this section, you will find information that will help you better understand functionalities of the WebCurrencyEditor control. Further,you will understand the purpose of the control.

== link:webcurrencyeditor-using-webcurrencyeditor.html[Using WebCurrencyEditor]

This section provides task-based information showing you how to use the features available in WebCurrencyEditor.

== link:webcurrencyeditor-accessibility-compliance.html[WebCurrencyEditor Accessibility Compliance]

This topic outlines the way in which WebCurrencyEditor meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebCurrencyEditor control.

== link:webcurrencyeditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebCurrencyEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtexteditor~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebCurrencyEditor™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.