////

|metadata|
{
    "name": "web-webdialogwindow",
    "controlName": ["WebDialogWindow"],
    "tags": [],
    "guid": "{9BC0900C-B019-49E2-897C-D9AD4BE1200E}",  
    "buildFlags": [],
    "createdOn": "2008-12-01T20:39:32Z"
}
|metadata|
////

= WebDialogWindow

If you're looking for an area that houses all of the overview/task-based information related to the WebDialogWindow™ control, you've come to the right place. This section contains valuable information about WebDialogWindow, ranging from what the control does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to access important information about the WebDialogWindow control.

== link:webdialogwindow-about-webdialogwindow.html[About WebDialogWindow]

In this section you'll find any information that will help you to better understand the functionalities of the WebDialogWindow control, as well as why you would want to use it to as part of building your applications.

== link:webdialogwindow-getting-started-with-the-webdialogwindow.html[Getting Started with WebDialogWindow]

In order to get you up and running as quickly as possible with the WebDialogWindow control, we've provided you with information on how to get started using the control (i.e., adding WebDialogWindow to a form).

== link:webdialogwindow-using-webdialogwindow.html[Using WebDialogWindow]

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by the WebDialogWindow control.

== link:webdialogwindow-webdialogwindow-accessibility-compliance.html[WebDialogWindow Accessibility Compliance]

This topic outlines the way in which WebDialogWindow meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebDialogWindow control.

== link:webdialogwindow-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebDialogWindow control. The namespaces and classes listed in this topic link conveniently into the link:web-api-reference-guide.html[API Reference Guide] section of the Infragistics ASP.NET help.

== link:webdialogwindow~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebDialogWindow control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the dialog window without the need for server-side post-backs.