////

|metadata|
{
    "name": "web-webpercenteditor",
    "controlName": ["WebPercentEditor"],
    "tags": [],
    "guid": "{7F412BEF-7CB1-42A0-8644-4177EB8CC710}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T11:54:31Z"
}
|metadata|
////

= WebPercentEditor

This page contains all of the overview/task-based information related to the WebPercentEditor™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebPercentEditor control.

== link:webpercenteditor-about-webpercenteditor.html[About WebPercentEditor]

In this section, you will find information that will help you better understand functionalities of the WebPercentEditor control. Further,you will understand the purpose of the control.

== link:webpercenteditor-using-webpercenteditor.html[Using WebPercentEditor]

This section provides task-based information showing you how to use the features available in WebPercentEditor.

== link:webpercenteditor-accessibility-compliance.html[WebPercentEditor Accessibility Compliance]

This topic outlines the way in which WebPercentEditor meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebPercentEditor control.

== link:webpercenteditor-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebPercentEditor control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtexteditor~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebPercentEditor™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.