////

|metadata|
{
    "name": "web-webdatagrid-webdatagrid",
    "controlName": ["WebDataGrid"],
    "tags": ["Getting Started","Grids"],
    "guid": "{384FD106-33AE-49A3-B1FB-422931D18619}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDataGrid

This page contains all of the overview/task-based information related to the WebDataGrid™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebDataGrid control.

== link:webdatagrid-about-webdatagrid.html[About WebDataGrid]

In this section, you will find information that will help you better understand functionalities of the WebDataGrid control. Further, you will understand the purpose of the control.

== link:webdatagrid-getting-started-with-webdatagrid.html[Getting Started with WebDataGrid]

This section provides you with information on how to get up and running as quickly as possible with the WebDataGrid control.

== link:webdatagrid-using-webdatagrid.html[Using WebDataGrid]

This section provides task-based information showing you how to use the features available in WebDataGrid.

== link:gridmigrationoverview.html[Migrating from UltraWebGrid to WebDataGrid and WebHierarchicalDataGrid]

This page contains all of the overview/task-based information related to WebDataGrid migration.

== link:webdatagrid-accessibility-compliance.html[WebDataGrid Accessibility Compliance]

This topic outlines the way in which WebDataGrid meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebDataGrid control.

== link:webdatagrid-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebDataGrid control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webdatagrid~infragistics.web.ui_namespace.html[CSOM Overview]

The WebDataGrid™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the WebDataGrid control without the need for server-side post-backs.