////

|metadata|
{
    "name": "web-webdatepicker",
    "controlName": ["WebDatePicker"],
    "tags": [],
    "guid": "{FD8E64D2-DC16-4F89-8013-0ED12DF4DE2D}",  
    "buildFlags": [],
    "createdOn": "2009-04-06T11:18:57Z"
}
|metadata|
////

= WebDatePicker

This page contains all of the overview/task-based information related to the WebDatePicker™ control. This section contains valuable information about the control, ranging from what it does and why you would want to use it in your application, to step-by-step procedures on how to accomplish a common task using the control.

Click the links below to learn about the WebDatePicker control.

== link:webdatepicker-about-webdatepicker.html[About WebDatePicker]

In this section, you will find information that will help you better understand functionalities of the WebDatePicker control. Further,you will understand the purpose of the control.

== link:webdatepicker-using-webdatepicker.html[Using WebDatePicker]

This section provides task-based information showing you how to use the features available in WebDatePicker.

== link:webdatepicker-accessibility-compliance.html[WebDatePicker Accessibility Compliance]

This topic outlines the way in which WebDatePicker meets the requirements of the Section 508 standards. This accessibility compliance allows your end users, specifically those with disabilities, to be able to access and use your Web application built using the WebDatePicker control.

== link:webdatepicker-api-overview.html[API Overview]

This topic lists the namespaces and classes that you will be working with while programming with the WebDatePicker control. The namespaces and classes listed in this topic link conveniently into the API Reference Guide section of the Infragistics ASP.NET help.

== link:webtexteditor~infragistics.web.ui_namespace.html[Client-Side Object Model (CSOM) Overview]

The WebDatePicker™ control exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledged JavaScript objects, and events that enable developers to program significant units of functionality pertaining to the control without the need for server-side post-backs.