////

|metadata|
{
    "name": "webcurrencyeditor-setting-minimum-number-of-decimal-places-for-webcurrencyeditor",
    "controlName": ["WebCurrencyEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{F4DC5C77-0554-4E20-9958-B54A614DECF4}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T17:11:31Z"
}
|metadata|
////

= Setting minimum number of decimal places for WebCurrencyEditor

WebCurrencyEditor™ allows you to set the number of decimal places you want to display to your end-user by simply setting the control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webcurrencyeditor~mindecimalplaces.html[MinDecimalPlaces]"]  property. If an end-user types a currency value with more or less decimal numbers than the number of decimal places set on the editor, then the editor rounds to the number of decimal places set on the editor.

You can set the MinDecimalPlaces property either by using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebCurrencyEditor1.MinDecimalPlaces = 3
----

*In C#:*

----
WebCurrencyEditor1.MinDecimalPlaces = 3;
----

*In JavaScript:*

----
$find("WebCurrencyEditor1").set_minDecimals(3);
----