////

|metadata|
{
    "name": "webcalendarview-accessibility-compliance",
    "controlName": ["WebCalendarView"],
    "tags": ["Section 508"],
    "guid": "{54DEA273-565A-41C7-8F51-8DF1BBD198CA}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebCalendarView Accessibility Compliance

All of our ASP.NET controls and components comply with section 508, subpart 1194.22 of the Rehabilitation Act of 1973. Below is a table containing the specific rules of subpart 1194.22 that pertain to the control, and how we comply with each rule. In some cases, you may have to set a property. In other cases, you won't have to do anything as our control does all the work for you.

[options="header", cols="a,a"]
|====
|Rules|How We Comply with the Rules

|(a)
|By enabling the control's pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.webscheduleviewbase~section508compliant.html[Section508Compliant]"] property, all non-text elements render a text equivalent. 

.Note:
[NOTE]
====
A text equivalent is supplied by default, but this can be customized to suit your needs. 
====

|(h)
|By enabling the control's Section508Compliant property, scope attributes are rendered to identify DayOfWeek headers as column headers, and WeekNumbers as row headers.

|====