////

|metadata|
{
    "name": "webcurrencyeditor-using-webcurrencyeditor",
    "controlName": ["WebCurrencyEditor"],
    "tags": [],
    "guid": "{AF79DAE4-13B4-41FD-B13D-005E78D5BAB7}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:25:07Z"
}
|metadata|
////

= Using WebCurrencyEditor

This section is your gateway to important task-based information that will help you to effectively use the various features and functionalities provided by WebCurrencyEditor™.

link:webcurrencyeditor-setting-minimum-and-maximum-values-for-webcurrencyeditor.html[Setting minimum and maximum values for WebCurrencyEditor]

In this section you can learn how to set minimum and maximum values for the WebCurrencyEditor control.

link:webcurrencyeditor-setting-minimum-number-of-decimal-places-for-webcurrencyeditor.html[Setting minimum number of decimal places for WebCurrencyEditor]

In this section you can learn how to set minimum and maximum number of decimal places for the WebCurrencyEditor control.

link:webcurrencyeditor-setting-the-culture-of-webcurrencyeditor.html[Setting the Culture of WebCurrencyEditor]

This section contains information about setting a specific culture for the WebCurrencyEditor control.

link:webcurrencyeditor-spinning-through-a-list-of-values-in-webcurrencyeditor.html[Spinning through a list of values in WebCurrencyEditor]

In this section you can learn how to use spin buttons in the control to spin through a list of values.

link:webcurrencyeditor-styling-negative-text-in-webcurrencyeditor.html[Styling negative text in WebCurrencyEditor]

You can learn how to set a custom style for negative text in this section.

link:webcurrencyeditor-using-custom-button-in-webcurrencyeditor.html[Using Custom Button in WebCurrencyEditor]

In this section you can learn how to implement a customized button and use it to perform custom actions.

link:webcurrencyeditor-using-display-factor-in-webcurrencyeditor.html[Using Display Factor in WebCurrencyEditor]

The WebCurrencyEditor control supports the usage of a display factor value that modifies the user input. This section explains how you can use it.

link:webcurrencyeditor-webcurrencyeditor-smart-tag.html[WebCurrencyEditor Smart Tag]

In this section you can learn about the WebCurrencyEditor Smart Tag.