////

|metadata|
{
    "name": "webcaptcha-configuring-captcha-input-field",
    "controlName": ["WebCaptcha"],
    "tags": ["Styling","Validation"],
    "guid": "a15b98f7-36be-4e38-8426-cfd09d6cae45",  
    "buildFlags": [],
    "createdOn": "2010-05-31T13:06:38.9598633Z"
}
|metadata|
////

= Configuring Captcha Input Field

When using the WebCaptcha™ control in Captcha (default) link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webcaptcha~protectionmode.html[ProtectionMode], the control renders a text input field, link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webcaptcha~inputvalueeditor.html[InputValueEditor], and its value is used for the captcha validation. The text input is the WebTextEditor control, and you may take advantage of all the features that it provides. The WebCaptcha control also provides the link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webcaptcha~captchaeditorid.html[CaptchaEditorID] property, which can be used to specify an external input field. Here is an example:

*In HTML:*

----
<ig:WebCaptcha ID="WebCaptcha1" runat="server" CaptchaEditorID="TextBox1">
</ig:WebCaptcha>
<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
----

== Related Topics

link:webcaptcha-protection-modes.html[Protection Modes]

link:webcaptcha-dictionary-modes.html[Dictionary Modes]

link:webcaptcha-captcha-validation.html[Captcha Validation]

link:webcaptcha-configuring-captcha-buttons.html[Configuring Captcha Buttons]

link:webcaptcha-configuring-captcha-image-properties.html[Configuring Captcha Image Properties]

link:webcaptcha-configuring-captcha-audio.html[Configuring Captcha Audio]