////

|metadata|
{
    "name": "webcurrencyeditor-setting-minimum-and-maximum-values-for-webcurrencyeditor",
    "controlName": ["WebCurrencyEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{BA5204A7-FF0D-4E01-A384-0DE3167843CE}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:39:53Z"
}
|metadata|
////

= Setting minimum and maximum values for WebCurrencyEditor

WebCurrencyEditor™ allows you to set a range of currency values that your end-user can enter into the editor by simply setting the control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~minvalue.html[MinValue]"]  and  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~maxvalue.html[MaxValue]"]  properties. If an end-user types a currency value more than the maximum value then the editor sets the value to the maximum value. Similarly, if an end-user types a currency value less than the minimum value then the editor sets the value to the minimum value.

You can set the MinValue and MaxValue properties either by using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebCurrencyEditor1.MinValue = 25
WebCurrencyEditor1.MaxValue = 100
----

*In C#:*

----
WebCurrencyEditor1.MinValue = 25;
WebCurrencyEditor1.MaxValue = 100;
----

*In JavaScript:*

----
var Editor = $find("WebCurrencyEditor1");
Editor.set_minValue(25);
Editor.set_maxValue(100);
----