////

|metadata|
{
    "name": "webcalendarview-csom",
    "controlName": [],
    "tags": ["API","Getting Started"],
    "guid": "{B3CD6040-C00E-4CB3-9355-DD8981098308}",  
    "buildFlags": [],
    "createdOn": "2005-07-12T00:00:00Z"
}
|metadata|
////

= WebCalendarView CSOM

WebCalendarView™ exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledge JavaScript objects, events, and utility functions that enable developers to program significant units of functionality pertaining to the WebCalendarView control without the need for server-side post-backs.

In general, the object model is derived directly from the object model as it exists on the server. The property names, events, parameters and return values have very similar meanings to their counterparts on the server. However, where noted, properties are sometimes read-only on the client. These properties are only for informational purposes and must not be altered.

Client-Side Object Model reference for the WebCalendarView control:

link:webcalendarview-utility-functions-csom.html[WebCalendarView Utility Functions]

link:webcalendarview-object-csom.html[WebCalendarView Object]

____
link:webcalendarview-client-side-events-csom.html[Client-Side Events]
____