////

|metadata|
{
    "name": "webchart-csom",
    "controlName": [],
    "tags": ["Getting Started"],
    "guid": "{927BE306-6886-4F48-BBF6-310DB9C956D2}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebChart CSOM

WebChart™ exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledge JavaScript events that enable developers to program significant units of functionality pertaining to the chart control without the need for server-side post-backs.

In general, the object model is derived directly from the object model as it exists on the server. The property names, events, parameters and return values have very similar meanings to their counterparts on the server. However, where noted, properties are sometimes read-only on the client. These properties are only for informational purposes and must not be altered.

Select one of the following sections of the Client-Side Object Model reference for the WebChart control:

link:webchart-client-side-events-csom.html[Client-Side Events]