////

|metadata|
{
    "name": "webdatagrid-configuring-multi-column-footers",
    "controlName": ["WebDataGrid"],
    "tags": ["Getting Started","Grids"],
    "guid": "47cf4f66-55cf-4d88-8c1a-2ca572d1da21",  
    "buildFlags": [],
    "createdOn": "2012-04-16T02:13:18.0439667Z"
}
|metadata|
////

= Configuring Multi-Column Footers

== Topic Overview

=== Purpose

This topic demonstrates, with code examples, how to configure multi-column footers in the  _WebDataGrid_™.

=== Required background

The following table lists the topics required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:webdatagrid-about-webdatagrid.html[About WebDataGrid]
|This topic describes the features of _WebDataGrid_ .

| link:webdatagrid-getting-started-with-webdatagrid.html[Getting Started with WebDataGrid]
|This topic explains how to bind the _WebDataGrid_ to the Northwind sample database.

| link:webdatagrid-columns.html[Columns]
|This topic explains how to configure _WebDataGrid_ columns using the designer.

| link:webdatagrid-add-or-remove-a-column.html[Add or Remove a Column]
|This topic explains how to add or remove column to _WebDataGrid_ in code.

|====

=== In this topic

This topic contains the following sections:

* <<_Ref321761870, Configuring Multi-Column Footers – Conceptual Overview >>
** <<_Ref321833477,Multi-column footers configuration summary>>
** <<_Ref321833481,Requirements>>
** <<_Ref321833485,Property settings>>

* link:webdatagrid-configuring-multi-column-footers.html#code_example[ *Configuring Multi-Column Footers – Code Example* ]
** <<_Ref321761894,Introduction>>
** <<_Ref321761898,Preview>>
** <<_Ref321761901,Prerequisites>>
** <<_Ref321761906,Overview>>
** <<_Ref321761909,Steps>>

* <<_Ref321765186, Related Content >>
** <<_Ref321833490,Topics>>
** <<_Ref321833493,Samples>>

[[_Control_Configuration_Summary]]
[[_Ref321761870]]
== Configuring Multi-Column Footers – Conceptual Overview

[[_Ref321833477]]

=== Multi-column footers configuration summary

The multi-column footer functionality allows you to merge multiple columns footers. This means that the text of the footer of one column is spread across several columns.

Configuring multi-column footers involves creating a link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfield_members.html[GridField] or its descendant instance and setting the link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfield~footer.html[Footer] property object. The link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfield~footer.html[Footer] property object is of class link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfieldfootercaption_members.html[GridFieldFooterCaption] and has link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfieldfootercaption~colspan.html[ColSpan] property. This property is responsible for configuring multi-column footers. After setting this property all you need to do is to set the footer text in the Text property of the link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfield~footer.html[Footer].

Unlike the multi-column header functionality there is no nesting of footers into a group. When configuring multi-column footers, you need to keep in mind the following:

*  *Merging is done left to right.*

When there is overlapping of merged columns, the rule for the left column has precedence over the rule for the right column and, as a result, the rule for right is discarded.

*  *Column span cannot go beyond the fixed region.*

When using multi-column footer with column fixing, the column span cannot go beyond the fixed region. For example, if there are 2 columns fixed and you define a footer span of 3 columns, the result will be only 2 column spans

*  *Colum spanning affects only visible columns.*

This means that columns are covered in the visible order rather than in their order in the collection. For example, if you have a visible column with column span 2, then a hidden column, and then another visible column, the second visible column will be included in the column span.

* Column spanning cannot go past the end of the grid.

For example, if there are 2 columns on the right of the grid and you define a 3-column span, the result will be a 2-column span.

.Note:
[NOTE]
====
You can span footers in  _GridField_   instances or its descendants.
====

[[_Ref321833481]]

=== Requirements

The  _WebDataGrid_   bound to data with link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.webdatagrid~showfooter.html[ShowFooter] property set to  _true_  .

[[_Ref321833485]]

=== Property settings

The following table lists the aspects in which multi-column footers can be configured and maps them to the respective properties that manage them.

[options="header", cols="a,a"]
|====
|Configurable aspect|Properties

|Number of columns
|
* link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfieldfootercaption~colspan.html[ColSpan] 

|====

[[_Configuring_Multi-Column_Footers]]
[[code_example]]
== Configuring Multi-Column Footers – Code Example

[[_Ref321761894]]

=== Introduction

In this example, the  _WebDataGrid_   is bound to the  _Suppliers_   table in the  _Northwind_   sample database. In order to display multi-column footers, column footers are enabled for the grid and column spans are defined for two of the columns. These are the  _SupplierID_   and  _Address_  columns.

[[_Ref321761898]]

=== Preview

The following screenshot is a preview of the final result.

image::images/Configuring_Multi-Column_Footers.docx(WDG)_1.png[]

[[_Ref321761901]]

=== Prerequisites

To complete the procedure, you need the following:

* A  _WebDataGrid_   bound to the  _Suppliers_   table of the  _Northwind_   sample database.

[[_Ref321761906]]

=== Overview

This topic takes you step-by-step toward configuring Multi-Column Footers in  _WebDataGrid_  . The following is a conceptual overview of the process:

 *1*  *.*  <<Configure_footer_visibility, Configure the footer visibility. >>

 *2*  *.*  <<Define_fields, Define the fields for the grid. >>

 *3*  *.*  <<Configure_Multi_column_footer, Configure the multi-column footer. >>

[[_Ref321761909]]

=== Steps

The following steps demonstrate how to configure Multi-Column Footers in  _WebDataGrid_  .

=== 1. Configure the footer visibility.

In order to set the footer set  _ShowFooter_   property to  _true_  .

*In ASPX:*

[source,html]
----
<ig:WebDataGrid ID="WebDataGridView" runat="server" ShowFooter="True" >
</ig:WebDataGrid>
----

*In C#:*

[source,csharp]
----
WebDataGridView.ShowFooter = true;
----

=== 2. Define the fields for the grid.

Define fields for the grid.

*In ASPX:*

[source,html]
----
<Columns>
    <ig:BoundDataField DataFieldName="SupplierID" Key="SupplierID">
        <Header Text="SupplierID" />
    </ig:BoundDataField>
    <ig:BoundDataField DataFieldName="CompanyName" Key="CompanyName">
        <Header Text="Company" />
    </ig:BoundDataField>
    <ig:BoundDataField DataFieldName="Address" Key="Address">
        <Header Text="Address" />
    </ig:BoundDataField>
    <ig:BoundDataField DataFieldName="City" Key="City">
        <Header Text="City" />
    </ig:BoundDataField>
    <ig:BoundDataField DataFieldName="PostalCode" Key="PostalCode">
        <Header Text="Postal Code" />
    </ig:BoundDataField>
</Columns>
----

*In C#:*

[source,csharp]
----
BoundDataField supplierId = new BoundDataField();
supplierId.DataFieldName = "SupplierID";
supplierId.Key = "SupplierID";
supplierId.Header.Text = "SupplierID";
WebDataGridView.Columns.Add(supplierId);
BoundDataField companyName = new BoundDataField();
companyName.DataFieldName = "CompanyName";
companyName.Key = "CompanyName";
companyName.Header.Text = "Company";
WebDataGridView.Columns.Add(companyName);
BoundDataField address = new BoundDataField();
address.DataFieldName = "Address";
address.Key = "Address";
address.Header.Text = "Address";
WebDataGridView.Columns.Add(address);
BoundDataField city = new BoundDataField();
city.DataFieldName = "City";
city.Key = "City";
city.Header.Text = "City";
WebDataGridView.Columns.Add(city);
BoundDataField postalCode = new BoundDataField();
postalCode.DataFieldName = "PostalCode";
postalCode.Key = "PostalCode";
postalCode.Header.Text = "Postal Code";
WebDataGridView.Columns.Add(postalCode);
----

=== 3. Configure the multi-column footer.

Add footers to the respective columns. In this example, the footers are added to the  _SupplierID_   and  _Address_   columns. *1*  *.*   *Add*   *a*   *foo*  *ter*   *to*   *the*   _SupplierID_    *column*   *and set*   *the*   _ColSpan_    *property*   *to 2*  *.* 

*In ASPX:*

[source,html]
----
<ig:BoundDataField DataFieldName="SupplierID" Key="SupplierID">
    <Header Text="SupplierID" />
    <Footer Text="SupplierID and Company Name footer" ColSpan="2" />
</ig:BoundDataField>
----

*In C#:*

[source,csharp]
----
BoundDataField supplierId = new BoundDataField();
supplierId.DataFieldName = "SupplierID";
supplierId.Key = "SupplierID";
supplierId.Header.Text = "SupplierID";
supplierId.Footer.Text = "SupplierID and Company Name footer";
supplierId.Footer.ColSpan = 2;
WebDataGridView.Columns.Add(supplierId);
----

*2*  *.*   *Add*   *a*   *footer*   *to*   *the*   _Address_    *column*   *and set*   *the*   _ColSpan_    *property*   *to 3*  *.*

*In ASPX:*

[source,html]
----
<ig:BoundDataField DataFieldName="Address" Key="Address">
    <Header Text="Address" />
    <Footer Text="Address and City and Postal Code footer" ColSpan="3" />
</ig:BoundDataField>
----

*In C#:*

[source,csharp]
----
BoundDataField address = new BoundDataField();
address.DataFieldName = "Address";
address.Key = "Address";
address.Header.Text = "Address";
address.Footer.Text = "Address and City and Postal Code footer";
address.Footer.ColSpan = 3;
WebDataGridView.Columns.Add(address);
----

[[_Related_Content]]
[[_Ref321765186]]
== Related Content

[[_Ref321833490]]

=== Topics

The following topics provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:webdatagird-multi-column-headers.html[Configuring WebDataGrid Multi-Column Headers]
|This topic demonstrates how to configure multi-column headers in the _WebDataGrid_ .

|====

[[_Ref321833493]]

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/samples/webdatagrid/display/multicolumnfooters/default.aspx?cn=data-grid&sid=bd7a3ca7-3396-4cc3-8e79-a4e2a36df682[Multi-Column Footers]
|This demonstrates configuring _WebDataGrid_ with multi-column footers.

|====