////

|metadata|
{
    "name": "webdatagrid-ajax-indicator-support-for-webdatagrid",
    "controlName": ["WebDataGrid"],
    "tags": ["Events","Grids"],
    "guid": "{D5032689-B524-4C39-9BF2-7D819EE942BE}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Ajax Indicator Support for WebDataGrid

The WebDataGrid™ control’s AJAX Indicator displays a wait notification for end users whenever the control is waiting for a callback to complete. By default, the AJAX indicator is shared with other Infragistics ASP.NET AJAX controls; however the shared AJAX Indicator settings can be overridden on the control level. The wait message is configurable to show text or an Image by, using the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.ajaxindicator~text.html[Text]"]  or the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.ajaxindicator~imageurl.html[ImageUrl]"]  property settings. You can also set the screen location of the indicator by using the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.ajaxindicator~location.html[Location]"]  property.

*In Visual Basic:*

----
' Enable Ajax Indicator at control level
Me.WebDataGrid1.AjaxIndicator.Enabled = Infragistics.Web.UI.DefaultableBoolean.[True] 
' Set the Ajax Indicator’s wait message 
Me.WebDataGrid1.AjaxIndicator.Text = "Ajax Call Wait" 
' Set the Ajax Indicator’s Location 
Me.WebDataGrid1.AjaxIndicator.Location = Infragistics.Web.UI.RelativeLocation.AboveCenter 
' Set the location of the Ajax Indicator specific to the control. 
Me.WebDataGrid1.AjaxIndicator.RelativeToControl = Infragistics.Web.UI.DefaultableBoolean.[True]
----

*In C#:*

----
// Enable Ajax Indicator at control level
this. WebDataGrid1.AjaxIndicator.Enabled = Infragistics.Web.UI.DefaultableBoolean.True;
// Set the Ajax Indicator’s wait message
this. WebDataGrid1.AjaxIndicator.Text = "Ajax Call Wait";
// Set the Ajax Indicator’s Location
this. WebDataGrid1.AjaxIndicator.Location = Infragistics.Web.UI.RelativeLocation.AboveCenter;
// Set the location of the Ajax Indicator specific to the control.
this. WebDataGrid1.AjaxIndicator.RelativeToControl = Infragistics.Web.UI.DefaultableBoolean.True;
----

== Related Topic

link:web-ajax-indicator.html[Configuring AJAX Indicator at Control level]