////

|metadata|
{
    "name": "webdialogwindow-allow-the-end-user-to-resize-the-dialog-window",
    "controlName": ["WebDialogWindow"],
    "tags": ["How Do I"],
    "guid": "{17F6627B-0075-4A43-8540-9CB17D17C759}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Allow the End User to Resize the Dialog Window

If you are using the dialog window as a simple prompt dialog box with a single OK button, your end users may not need to resize it. However, if you are displaying a large amount of information, or even an entire web page in the dialog window, the end user may need more room to comfortably view all of the dialog window's contents. If you set the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.resizer~enabled.html[Enabled]"]  property off the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.resizer.html[Resizer]"]  object to True, the end user will be able to resize the dialog window to as large or small as they need it to comfortably view their data. Enabling the resizer displays a small resizing image in the lower, right corner of the dialog window. End users can grab this resizer and drag the dialog window until it is the right size for their taste.

The following code demonstrates how to enable the resizer.

*In Visual Basic:*

----
' Allow the End User to Resize the Dialog Window.
Me.WebDialogWindow1.Resizer.Enabled = True
----

*In C#:*

----
// Allow the End User to Resize the Dialog Window.
this.WebDialogWindow1.Resizer.Enabled = true;
----