////

|metadata|
{
    "name": "webdropdown-multi-mode-display",
    "controlName": ["WebDropDown"],
    "tags": [],
    "guid": "{09A7DA98-A28B-4CFD-87ED-89CADC3B1D3C}",  
    "buildFlags": [],
    "createdOn": "2009-03-03T13:40:36Z"
}
|metadata|
////

= Multi-mode Display

WebDropDown™ allows you to specify one of several different behavioral modes. For instance, you may want your end-users to simply select from a list of values without allowing them to type into the drop-down editor. Other times, you may want your end-users to type into the drop-down editor and try to find a list item by auto-filtering. You may even want to use WebDropDown as a read-only lookup control where the display value represents a user-friendly string that comes from a lookup table so that you do not have to present meaningless foreign key values to your end-users. These behavioral modes are a functionality of the WebDropDown control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.listcontrols.webdropdown~displaymode.html[DisplayMode]"]  property.

The following is a list of WebDropDown display modes:

*DropDownList*

* The end-user will be able to select an item from the value list.
* No editing of the display value will be allowed.
* No auto filtering.
* The end-user will be able to display the drop-down.

*DropDown*

* The end-user will be able to select an item from the value list.
* Editing of the display value will be allowed.
* Auto filtering can be done.
* The end-user will be able to display the drop-down.

*ReadOnly*

* The end-user will not be able to select an item from the value list.
* No editing of the display value will be allowed.
* No auto filtering.
* The end-user will not be able to display the drop-down.

*ReadOnlyList*

* The end-user will not be able to select an item from the value list.
* No editing of the display value will be allowed.
* No auto filtering.
* The end-user will be able to display the drop-down.

.Note:
[NOTE]
====
When the control provides both display and value properties or when templating is used, the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.listcontrols.webdropdown~textfield.html[TextField]"]  property should be set.
====

You can set the DisplayMode property either using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebDropDown1.DisplayMode = Infragistics.Web.UI.ListControls.DropDownDisplayMode.ReadOnlyList
----

*In C#:*

----
WebDropDown1.DisplayMode = Infragistics.Web.UI.ListControls.DropDownDisplayMode.ReadOnlyList;
----