////

|metadata|
{
    "name": "webdatagrid-accessibility-compliance",
    "controlName": ["WebDataGrid"],
    "tags": ["Section 508"],
    "guid": "{4185BBA7-A29C-466B-A87C-11E88053B5AA}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDataGrid Accessibility Compliance

All of our ASP.NET controls and components comply with section 508, subpart 1194.22 of the Rehabilitation Act of 1973 to varying degrees. For an overview of compliance across controls, link:web-accessibility-overview.html[refer to the table here]. Below is a table containing the specific rules of subpart 1194.22 that pertain to the WebDataGrid control, and how we comply with each rule. In some cases, you may have to set a property. In other cases, you won't have to do anything as our control does all the work for you.

If you do not see the section listed here, it means that the control does not comply with that section or it is not applicable.

[options="header", cols="a,a"]
|====
|Rules|How We Comply with the Rules

|(a)
|All IMG tags, which have key functionality, have "alt" attributes property set or allow for setting of the alt attribute value.

|(c)
|Using client side events, the user can change any attribute of any of the control's DOM element reflecting the current state (activate, selected, disabled and so on...) In this way, the information conveyed by colors (or styles) are available to the screen reader. You can also use CSS to style WebDataGrid™ in any color (black/white as well).

|(l)
|When the control's scripts are changing the page markup, the new created content comply with the screen reader due to the attributes described in rules (a) and (c).

|(n)
|By setting the control's TabIndex property to a value higher than 0, the control will participate in the tab sequence of the page, and receive focus. 

* TAB -- Makes the next row/cell active. 

* SHIFT+TAB -- Makes the previous row/cell active. 

* CTRL+TAB -- Switches between an active row and an active cell. 

* Spacebar -- If the active cell is a checkbox, toggles its checked state; otherwise, selects/deselects the active row. 

* LEFT ARROW -- When a cell is active, makes the previous cell active. When a row is active, collapses the child row island (if any). 

* RIGHT ARROW -- When a cell is active, makes the next cell active. When a row is active, expands the child row island (if any). 

* UP ARROW -- Makes the row/cell in the previous row active. 

* DOWN ARROW -- Makes the row/cell in the next row active. 

* SHIFT+UP (or DOWN) ARROW -- Includes the above (or below) row in a multiple-row selection. 

* ENTER / PAGE DOWN -- Triggers a click if the cell is a cell button. Navigates to a cell's Target URL, if any exists; otherwise takes you to the next row. 

* SHIFT & ENTER / PAGE UP -- Take you to the previous row 

* DEL -- Deletes the current row. 

When the Batch Update feature is enabled: 

* ENTER/SPACE – when a row is deleted, an Undo button appears when hovering the mouse pointer over a deleted row. Pressing either the ENTER or SPACE keys activates the Undo button (and recovers the row) just like a mouse click would do. 

* CTRL+ Z – undoes the changes (edits) made to a row. 

|(o)
|You can achieve this through some of the navigation keys mentioned for (n).

|====