////

|metadata|
{
    "name": "webdatatree-load-on-demand",
    "controlName": ["WebDataTree"],
    "tags": [],
    "guid": "{8545E3C6-F754-43C9-AB37-B20CD0FA2782}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Load-on-demand

WebDataTree™ supports load-on-demand functionality. When load-on-demand is enabled you can avoid any excessive initial processing of the page.

*Using Load-on-demand in WebDataTree.*

WebDataTree™ handles very large amounts of data without incurring any loss in performance with its load-on-demand feature enabled. You can decide on how many nodes to initially load by setting the WebDataTree control’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.navigationcontrols.webdatatree~initialdatabinddepth.html[InitialDataBindDepth]"]  property. By default, the InitialDataBindDepth property is set to -1, which means all the nodes are initially loaded. The value that you specify for the InitialDataBindDepth property represents the index of the last level that is to be initially loaded. For example, if you set this property to a value of 1, then level 0 (the first level of nodes) and level 1 (the second level of nodes) will be loaded upon the initial page rendering. Subsequent levels with an index of 2, 3 and so forth will be loaded on demand.

If you want to learn how to use load-on-demand in WebDataTree, follow this steps.

[start=1]
. From the Visual Studio™ Toolbox, drag and drop a ScriptManager component, a WebDataTree control and a WebHierarchicalDataSource control.
[start=2]
. Bind the WebDataTree to WebHierarchicalDataSource as shown in the link:webdatatree-binding-webdatatree-to-webhierarchicaldatasource.html[Binding WebDataTree to WebHierarchicalDataSource] topic.
[start=3]
. Set the InitialDataBindDepth and DataLoadingMessage properties as shown in the following code :

*In Visual Basic:*

----
        WebDataTree1.InitialDataBindDepth = 0
        WebDataTree1.DataLoadingMessage = "Loading...Please wait!"
----

*In C#:*

----
        WebDataTree1.InitialDataBindDepth = 0;
        WebDataTree1.DataLoadingMessage = "Loading...Please wait!";
----

In the above code, setting the InitialDataBind property to 0 allows only the first level of nodes to be bound to the tree. The remaining nodes will be bound on demand.
[start=4]
. Save and run your application. You will observe that when you expand the nodes, the data loading message “Loading…Please wait!” will appear first and then the corresponding child nodes are loaded.

*Using data loading template in WebDataTree.*

When using the load-on-demand feature, WebDataTree allows you to show a customized loading message by setting the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.navigationcontrols.webdatatree~dataloadingmessage.html[DataLoadingMessage]"]  property. However you can also apply a data loading template to the loading message using the WebDataTree control’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.navigationcontrols.webdatatree~dataloadingtemplate.html[DataLoadingTemplate]"]  property.  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.navigationcontrols.webdatatree~dataloadingtemplatecontainer.html[DataLoadingTemplateContainer]"]  is the container control for the WebDataTree control’s data loading template. If you want to set and use template for WebDataTree loading message, follow the next steps.

[start=1]
. From the Visual Studio™ Toolbox, drag and drop a ScriptManager component and a WebDataTree control onto the form.
[start=2]
. In the source code, include the following code between the WebDataTree tags to show the loading message using the DataLoadingTemplate tags.

*In HTML :*

----
<DataLoadingTemplate>
                <div id="loadTemplate" style="background-color : Aqua">
                    <span id="actualMsg">Loading, please wait…</span>
                </div>
</DataLoadingTemplate>
----

[start=3]
. Save and run your application. When you expand the nodes for the first time, you will observe that the data loading template is applied to the loading message.