////

|metadata|
{
    "name": "webdropdown-autocomplete-and-auto-filtering",
    "controlName": ["WebDropDown"],
    "tags": [],
    "guid": "{F6184A30-C023-437E-A146-B8715CF1C18B}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Autocomplete and Auto Filtering

== Autocomplete

WebDropDown™ supports the autocomplete feature which causes the dropdown container to display automatically and show the first possible match in the value display as you type into the input box and by scrolling through the items so that the first match is on the top of the list. However the drop-down items list is not modified in this case. This functionality is enabled by default.


.Note:
[NOTE]
====
The autocomplete feature works only when the WebDropDown control’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~displaymode.html[DisplayMode]"]  property is set to DropDown.
====


When the end-user starts typing into WebDropDown , the first possible match from the drop-down list is displayed in the value display and the appended characters are selected in the value display (the delta characters). This functionality which is enabled by setting the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~enableautocompletefirstmatch.html[EnableAutoCompleteFirstMatch]"]  property works even when the drop-down container is not shown or disabled.

You can set the EnableAutoCompleteFirstMatch property either using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

[source]
----
WebDropDown1.EnableAutoCompleteFirstMatch = false
----

*In C#:*

[source]
----
WebDropDown1.EnableAutoCompleteFirstMatch = false;
----

== Auto Filtering

WebDropDown supports client-side or server-side auto filtering. As the end user begins to type into the editable textbox, the WebDropDown attempts to match the entered values in the underlying data source by initiating an AJAX callback .This can be configured by setting the WebDropDown control’s link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~enableautofiltering.html[EnableAutoFiltering] property to Client or Server. By default , this property is set to Off.When the EnableAutoFiltering Property is set to :

* *Off* -- Only finding, selecting, activating and scrolling to the first match is performed.
* *Client* -- The filtering is performed only on the client-side items collection contents, with no postbacks taking place.
* *Server* -- The filtering is performed on all the items in the drop-down list on the server by making AJAX callbacks. The link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~autofiltertimeoutms.html[AutoFilterTimeoutMs]  property controls the timeout until an AJAX request is made which is particularly useful for a slow connection or when the end-users type slowly.

.Note:
[NOTE]
====
When paging or load-on-demand is enabled, an AJAX callback will be initiated and filtering is done on the whole dataset on the server.
====

You can set the EnableAutoFiltering property either using the Visual Studio Property Window or by using the following code :

*In Visual Basic:*

[source]
----
WebDropDown1.EnableAutoFiltering = Infragistics.Web.UI.ListControls.AutoFiltering.Client
----

*In C#:*

[source]
----
WebDropDown1.EnableAutoFiltering = Infragistics.Web.UI.ListControls.AutoFiltering.Client;
----

== Configuring the filtering queries:

The autocomplete feature will work using a StartsWith query by default; however, this can be configured by setting the WebDropDown control’s link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~autofilterquerytype.html[AutoFilterQueryType]  property to one of the following options:

* StartsWith
* EndsWith
* Contains
* DoesNotContain
* Equals
* DoesNotEqual

You can set the AutoFilterQueryType property either using the Visual Studio Property Window or by using the following code :

*In Visual Basic:*

----
WebDropDown1.AutoFilterQueryType = Infragistics.Web.UI.ListControls.AutoFilterQueryTypes.EndsWith
----

*In C#:*

----
WebDropDown1.AutoFilterQueryType = Infragistics.Web.UI.ListControls.AutoFilterQueryTypes.EndsWith;
----

== Setting the number of displayed search results in the drop-down container :

You can set the number of search results to be displayed in the drop-down container by setting the WebDropDown control’s link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~autofilterresultsize.html[AutoFilterResultSize]  property. You can set the AutoFilterResultSize property either using the Visual Studio Property Window or by using the following code:

*In Visual Basic:*

----
WebDropDown1.AutoFilterResultSize = 10
----

*In C#:*

----
WebDropDown1.AutoFilterResultSize = 10;
----

== Search results Sort order:

Search results Sorting can be configured for ascending or descending order by setting the WebDropDown control’s  link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~autofiltersortorder.html[AutoFilterSortOrder]  property to *Ascending* or *Descending* . By default this property is set to None.

You can set the AutoFilterSortOrder property either using the Visual Studio property window or by using the following code:

*In Visual Basic:*

[source]
----
WebDropDown1.AutoFilterSortOrder = Infragistics.Web.UI.ListControls.DropDownAutoFilterSortOrder.Descending
----

*In C#:*

[source]
----
WebDropDown1.AutoFilterSortOrder = Infragistics.Web.UI.ListControls.DropDownAutoFilterSortOrder.Descending;
----

== Caching of filtering results on the client :

Caching of filtering results on the client is possible by setting the  link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webdropdown~enablecachingonclient.html[EnableCachingOnClient]  property. It works only when the EnableAutoFiltering property is set to Server. For instance, when subsequent queries for the same string are performed, the results for the second and other filtering operations are obtained from the client cache and no postback will be made to the server. By default this property is set to False.

You can set the EnableCachingOnClient property either using the Visual Studio property window or by using the following code:

*In Visual Basic:*

[source]
----
WebDropDown1.EnableCachingOnClient = false
----

*In C#:*

[source]
----
WebDropDown1.EnableCachingOnClient = false;
----