////

|metadata|
{
    "name": "webdialogwindow-maintain-the-headers-width-on-minimize",
    "controlName": ["WebDialogWindow"],
    "tags": ["How Do I"],
    "guid": "{5E3A038C-1832-447F-A9E7-BF4FCDC82AAE}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Maintain the Header's Width on Minimize

If you are allowing your end users to minimize the WebDialogWindow™ controls dialog window through the minimize box, the dialog window automatically hides the content pane and decreases the header's width to 100 pixels. If you would prefer to keep the header's width the same when it is minimized, then you will need to set the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.dialogwindowheader~minimizedwidth.html[MinimizedWidth]"]  property off the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.dialogwindowheader.html[Header]"]  object. An easy way to maintain the width of the header is to set the MinimizedWidth property to the same value as the dialog window's width. You can access the dialog window's width with the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.webdialogwindow~width.html[Width.Value]"]  property.

.Note:
[NOTE]
====
The Value property returns a double, and the MinimizedWidth property is of type int. Therefore, you'll need to cast the double to int.
====

The following code demonstrates how to maintain the width of the dialog window when minimizing it.

*In Visual Basic:*

----
' Maintain the Header's Width on Minimize.
    Me.WebDialogWindow1.Header.MinimizedWidth = _
        CType(Me.WebDialogWindow1.Width.Value, Integer)
----

*In C#:*

----
// Maintain the Header's Width on Minimize.
this.WebDialogWindow1.Header.MinimizedWidth = 
	(int)this.WebDialogWindow1.Width.Value;
----