////

|metadata|
{
    "name": "webdialogwindow-remove-the-header",
    "controlName": ["WebDialogWindow"],
    "tags": ["How Do I"],
    "guid": "{1C66EFF4-3F75-4EC2-B815-0897576C8880}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Remove the Header

The dialog window's header can be extremely valuable to the end user in regards to managing the dialog window itself. However, if your application's needs require you to do so, you can completely remove the header from the dialog window and handle all dialog window states through the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.webdialogwindow~windowstate.html[WindowState]"]  property. You can remove the dialog window's header by setting the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.layoutheader~visible.html[Visible]"]  property off the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.webdialogwindow~header.html[Header]"]  object to False. However, once the header is removed, you'll have to expose other ways for your end user to minimize, maximize, or close the dialog window; you'll also lose the ability to display a descriptive caption.

The following code demonstrates how to remove the header from the dialog window.

*In Visual Basic:*

----
' Remove the Header.
Me.WebDialogWindow1.Header.Visible = False
----

*In C#:*

----
 // Remove the Header.
this.WebDialogWindow1.Header.Visible = false;
----