////

|metadata|
{
    "name": "webdatagrid-enabling-cell-merging",
    "controlName": ["WebDataGrid"],
    "tags": ["Grids","Grouping"],
    "guid": "c90233ac-b79d-4a94-ba95-f52fad8ffe2d",  
    "buildFlags": [],
    "createdOn": "2012-04-12T19:11:47.5706741Z"
}
|metadata|
////

= Enabling Cell Merging

=== Purpose

This topic demonstrates, with code examples, how to enable the Cell Merging feature of the  _WebDataGrid_™.

=== Required background

The following table lists the materials required as a prerequisite to understanding this topic.

[options="header", cols="a,a"]
|====
|Topic|Purpose

| link:webdatagrid-sorting.html[Sorting]
|This topic explains, with code examples, how to enable sorting for the users of the _WebDataGrid_ .

| link:webdatagrid-cell-merging-overview.html[Cell Merging Overview (WebDataGrid)]
|This topic provides an overview of the Cell Merging feature of the _WebDataGrid_ .

|====

== Enabling Cell Merging

=== Overview

By default, link:webdatagrid-cell-merging.html[Cell Merging] is disabled. To enable it, you need to have the sorting behavior enabled and set the link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.sorting~enablecellmerging.html[EnableCellMerging] property to  _true_  . By default, Cell Merging is handled on the server side. If you don’t want to make requests to the server, you can render Cell Merging on the client side.

=== Property settings

The following table maps the desired Enable Cell Merging to property settings.

[options="header", cols="a,a,a"]
|====
|In order to:|Use this property:|And set it to:

|Enable Cell Merging
| link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.sorting~enablecellmerging.html[EnableCellMerging]
| _true_ 

|====

== Code Examples

=== Description

The following code snippets demonstrate how to enable Cell Merging with server-side and with client-side rendering.

=== Code example: enabling Cell Merging with server-side rendering

*In ASPX:*

[source,html]
----
<ig:WebDataGrid ID="WebDataGrid1"
                runat="server">
<Behaviors>
  <ig:Sorting Enabled="true" EnableCellMerging="true">
</ig:Sorting>
</Behaviors>
</ig:WebDataGrid>
----

*In C#:*

[source,html]
----
this.WebDataGrid1.Behaviors.Sorting.EnableCellMerging = true;
----

=== Code example: enabling Cell Merging with client-side rendering

*In ASPX:*

[source,html]
----
<ig:WebDataGrid ID="WebDataGrid1"
                runat="server" EnableClientRendering="true">
<Behaviors>
  <ig:Sorting Enabled="true" EnableCellMerging="true">
</ig:Sorting>
</Behaviors>
</ig:WebDataGrid>                              
----

*In C#:*

[source,html]
----
this.WebDataGrid1.EnableClientRendering = true;
this.WebDataGrid1.Behaviors.Sorting.EnableCellMerging = true;
----

== Related Content

=== Samples

The following samples provide additional information related to this topic.

[options="header", cols="a,a"]
|====
|Sample|Purpose

| link:{SamplesURL}/samples/webdatagrid/organization/sortingcellmerging/default.aspx?cn=data-grid&sid=bc564381-8ac9-4bb6-84e1-7c36e8010857[Cell Merging with Sorting]
|This sample demonstrates the cell merging capabilities of the sorting behavior of the WebDataGrid.

|====