////

|metadata|
{
    "name": "webdatagrid-excelstylefiltering-propertyreference",
    "controlName": ["WebDataGrid"],
    "tags": ["Filtering","Grids"],
    "guid": "1c76a9d5-d7ac-4d35-8ddf-a489ed734f16",  
    "buildFlags": [],
    "createdOn": "2012-07-16T12:51:56.3146029Z"
}
|metadata|
////

= Excel Style Filtering Property Reference

== Property Reference

=== Introduction

This topic provides reference information about the properties that are specific to the link:webdatagrid-excelstylefiltering-overview.html[Excel-Style Filtering] feature of the  _WebDataGrid_™ control.

=== Property reference chart

The following table summarizes the purpose and functionality of properties of the Excel-Style Filtering feature of the  _WebDataGrid_   control.

[options="header", cols="a,a"]
|====
|Property|Description

| link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.filtering~uniquevaluecasing.html[UniqueValueCasing]
|Configures the capitalization of the items in the filtering drop-down list.The allowed values are: 

* _Lower_ (Default) – the items appear in lowercase letters 

* _Upper_ – the items appear in uppercase letters (all caps) 

* _Camel_ – the items appear with sentence capitalization (Only the first letter of the item is capitalized.) 

| link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.filtering~nullvaluetext.html[NullValueText]
|Configures the value for the items in the filtering drop-down for a column with Null values in the data source.

|====