////

|metadata|
{
    "name": "webdatagrid-batch-updating-summaries",
    "controlName": ["WebDataGrid"],
    "tags": ["Drilldown","Editing","Events","Grids","Summaries"],
    "guid": "f3053075-8f94-4aff-85e5-20d83bb3a5b6",  
    "buildFlags": [],
    "createdOn": "2011-10-26T07:23:53.8214003Z"
}
|metadata|
////

= Summaries

This topic explains how batch updating works with Summaries including a special case in which the new summary cannot be calculated.

== Introduction

The batch updating feature is compatible with Summaries. When you modify a row, the column summaries are immediately affected and recalculated on the client without performing a postback to the server.

== Special Case: a Summary Cannot Be Calculated

There is only one special case in which it is not possible to recalculate the new summary on the client. This can happen if the data required for calculating is not (or might not be) available on the client, for example when paging is enabled.

For example, when user delete a row that contains either a minimum or maximum value or just edit a cell containing such value, then the new minimum/maximum should be calculated. But if the new minimum/maximum value is not available on the client or if you are unsure whether it is available and cannot check this, you cannot retrieve the new minimum/maximum.

In such cases, a special event, called “SummaryRowClientEvents-CalculateSummary”, is fired. It can be handled by you, as the developer, and you can decide, for example, to set a new value or make some modifications to the event arguments and then force a postback and accept the changes. You can also revert the deleted changes on the client side and make no postbacks. If you leave this event unhandled, then automatic postback is called internally and the new extreme value is calculated automatically.

For other summary values like Count, Average, and Sum, all recalculations take place on the client.

To attach to the SummaryRowClientEvents-CalculateSummary event, use this line of codes:

*In ASPX:*

----
<ig:WebDataGrid ID="wdg1" runat="server">
    <Behaviors>
        <ig:EditingCore BatchUpdating="true">
            <Behaviors>
                <ig:RowAdding/>
                <ig:RowDeleting/>
                <ig:CellEditing/>
            </Behaviors>
        </ig:EditingCore>
        <ig:SummaryRow 
             SummaryRowClientEvents-CalculateSummary="wdg1CalculateSummary">
        </ig:SummaryRow>
        <ig:Selection 
             CellClickAction="Row" RowSelectType="Multiple"></ig:Selection>
        <ig:Paging></ig:Paging>
    </Behaviors>
</ig:WebDataGrid>
----

And define handler using javascript code:

*In Javascript:*

----
function wdg1CalculateSummary(sender, eventArgs) {
}
----

For a real-life code example about how to handle the SummaryRowClientEvents-CalculateSummary event, refer to the Batch Update Summary sample.

== Related Topics

link:webdatagird-batch-updating-overview.html[WebDataGrid Batch Updating Overview]

link:webdatagrid-batch-updating-enabling.html#_enabling_batch_updating[Enabling Batch Updating in the WebDataGrid]

link:webdatagrid-batch-updating-events.html[WebDataGrid Batch Updating Events]

link:known-issues-known-issues-and-breaking-changes.html[Known Issues and Limitations]

== Related Samples

link:{SamplesURL}/samples/webdatagrid/editingandselection/batchupdatingsummaries/default.aspx?cn=data-grid&sid=0e6ba7c3-04b0-46d7-af6b-d0cadafda185[Batch Update Summary]