////

|metadata|
{
    "name": "webgauge-csom",
    "controlName": [],
    "tags": ["API","Data Presentation"],
    "guid": "{F122DE61-39D5-4EE5-AD6A-E50FDE1AA402}",  
    "buildFlags": [],
    "createdOn": "2007-06-02T11:52:30Z"
}
|metadata|
////

= WebGauge CSOM

WebGauge™ exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledge JavaScript objects, events, and utility functions that enable developers to program significant units of functionality pertaining to the WebGauge control without the need for server-side post-backs.

In general, the object model is derived directly from the object model as it exists on the server. The property names, events, parameters and return values have very similar meanings to their counterparts on the server. However, where noted, properties are sometimes read-only on the client. These properties are only for informational purposes and must not be altered.

Select one of the following sections of the Client-Side Object Model reference for the WebGauge control:

link:webgauge-utility-functions.html[Utility Functions]

link:webgauge-object.html[WebGauge Object]