////

|metadata|
{
    "name": "webgauge-apply-the-solid-brush-element-at-run-time",
    "controlName": ["WebGauge"],
    "tags": ["How Do I"],
    "guid": "{29D0B7D3-56E4-43D3-9A0B-9DCD6CBF3ED5}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Apply the Solid Brush Element at Run Time

Applying the Texture brush element to a property of your gauge gives the property a textured look and feel such as a canvas.

*To apply the Texture brush element to a property of your gauge using code:*

[start=1]
. Before you start writing any code, you should place using/Imports directives in your code-behind so you don't need to always type out a member's fully qualified name.

*In Visual Basic:*

----
Imports Infragistics.UltraGauge.Resources
----

*In C#:*

----
using Infragistics.UltraGauge.Resources;
----

[start=2]
. Create the load event.
[start=3]
. Create instances of the classes:

*In Visual Basic:*

----
Dim myTextureBrushElement As New TextureBrushElement()
Dim myRadialGauge As RadialGauge = Me.UltraGauge1.Gauges(0)
----

*In C#:*

----
TextureBrushElement myTextureBrushElement = new TextureBrushElement();
RadialGauge myRadialGauge = this.ultraGauge1.Gauges[0] as RadialGauge;
----

[start=4]
. Set the following properties:

** end color -- Silver
** start color -- DimGray
** texture style -- Canvas.

*In Visual Basic:*

----
myTextureBrushElement.EndColor = System.Drawing.Color.Silver
myTextureBrushElement.StartColor = System.Drawing.Color.DimGray
myTextureBrushElement.Texture = Infragistics.UltraGauge.Resources.Texture.Canvas
myRadialGauge.Dial.BrushElement = myTextureBrushElement
----

*In C#:*

----
myTextureBrushElement.EndColor = System.Drawing.Color.Silver;
myTextureBrushElement.StartColor = System.Drawing.Color.DimGray;
myTextureBrushElement.Texture = Infragistics.UltraGauge.Resources.Texture.Canvas;
myRadialGauge.Dial.BrushElement = myTextureBrushElement;
----

== Related Topics

link:webgauge-texture-brush-element.html[Texture Brush Element]

link:webgauge-apply-the-texture-brush-element-at-design-time.html[Apply the Texture Brush Element at Design Time]

link:webgauge-apply-the-texture-brush-element-using-the-gauge-designer.html[Apply the Texture Brush Element Using the Gauge Designer]