////

|metadata|
{
    "name": "webgauge-properties-panel",
    "controlName": ["WebGauge"],
    "tags": ["How Do I"],
    "guid": "{8FC09236-57D9-4E85-B445-470E6583515F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Properties Panel

The Properties panel of the Gauge Designer displays the properties of the currently selected gauge. For more information about the Properties panel, see link:webgauge-about-properties-panel.html[About Properties Panel].

The Properties panel is designed using tabs. These tabs allow you to edit the properties of the gauge. The tabs are divided into the following categories:

* link:webgauge-changing-the-layout-of-your-webgauge.html[Changing the Layout of Your WebGauge]
* link:webgauge-changing-the-appearance-of-your-webgauge.html[Changing the Appearance of Your WebGauge]
* link:webgauge-changing-the-annotations-on-your-webgauge.html[Changing the Annotations on Your WebGauge]
* link:webgauge-applying-effects-to-your-webgauge.html[Applying Effects to Your WebGauge]