////

|metadata|
{
    "name": "webhtmleditor-csom",
    "controlName": [],
    "tags": ["API","Editing"],
    "guid": "{E89FA7EF-107E-443F-8375-A399DFF9E91E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebHtmlEditor CSOM

WebHtmlEditor™ exposes a robust object model within the client-side JavaScript programming environment. The object model consists of full-fledge JavaScript objects, events, and utility functions that enable developers to program significant units of functionality pertaining to the html editor control without the need for server-side post-backs.

In general, the object model is derived directly from the object model as it exists on the server. The property names, events, parameters and return values have very similar meanings to their counterparts on the server. However, where noted, properties are sometimes read-only on the client. These properties are only for informational purposes and must not be altered.

Select one of the following sections of the Client-Side Object Model reference for the WebHtmlEditor control:

link:webhtmleditor-utility-functions-csom.html[WebHtmlEditor Utility Functions]

link:webhtmleditor-object-csom.html[WebHtmlEditor Object]

____
link:webhtmleditor-client-side-events-csom.html[Client-Side Events]
____