////

|metadata|
{
    "name": "webhtmleditor-hide-the-tab-strip-of-webhtmleditor",
    "controlName": ["WebHtmlEditor"],
    "tags": ["Editing"],
    "guid": "{F8D3017C-4AA1-4E90-B0B1-BD55681073D5}",  
    "buildFlags": [],
    "createdOn": "2006-04-01T00:00:00Z"
}
|metadata|
////

= Hide the Tab Strip of WebHtmlEditor

The Tab Strip region is automatically shown at the bottom of the WebHtmlEditor™ control when you use the control in your applications. Sometimes your application may not require users to access HTML view, and in these situations you should hide the Tab Strip region. Hiding a WebHtmlEditor region can be done in the design-time environment, or using code. In this example, code is added to the code-behind file to hide the tab strip at run time.

The WebHtmlEditor has a property called  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.webhtmleditor~tabstripdisplay.html[TabStripDisplay]"]  property that defaults to True. To hide the Tab Strip region, set this property to False with the following assignment statement from the Page_Load event handler

*In Visual Basic:*

----
Private Sub Page_Load(ByVal sender As System.Object, _
  ByVal e As System.EventArgs) Handles MyBase.Load
	Me.WebHtmlEditor1.TabStripDisplay = False
End Sub
----

*In C#:*

----
private void Page_Load(object sender, System.EventArgs e)
{
	this.WebHtmlEditor1.TabStripDisplay = false;
}
----