////

|metadata|
{
    "name": "webhierarchicladatagrid-column-templates",
    "controlName": ["WebHierarchicalDataGrid"],
    "tags": ["Grids","Templating"],
    "guid": "{1E1C751B-DF4F-41E5-AD80-4E462411AEBA}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Column Templates

WebHierarchicalDataGrid™ has four types of templates for its columns: header, footer, item, and alternating item templates. As the name implies, these templates take the place of the header, footer, and individual items of a column.

== Custom Columns

WebHierarchicalDataGrid™ provides the ability to create custom columns using column templates. You can embed any control within the template creating a unique look-and-feel for your column along with custom functionality.

== Column Templates

You can provide a cell, alternate cell, header, and footer template for a column. Setting a specific template for a column means the template will render in place of the element. For example, specifying an item template for a column will create a template for every cell in that column.

You can also specify an item template without making the entire column a template column. Each cell in a column has a  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.itemtemplate~template.html[Template]"]  and a  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.itemtemplate~templateid.html[TemplateId]"]  property. You can set either one of these properties to define a template for an individual cell.

== Referencing a Control within a Template

You can access a control within an item template by accessing that item and calling its  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.controldataitem~findcontrol.html[FindControl]"]  method.

As for the Header and Footer templates, you can use the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.fieldcaption~templatecontainer.html[TemplateContainer]"]  property off of each object to get reference to the template. Use the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.controldataitem~findcontrol.html[FindControl]"]  method to find the control.

== Template Editing

Templates for a column are just HTML within the column. You need to make the column read-only to prevent editing of the HTML. Doing this allows your end-users to edit using any editors in the template but prevent them from editing the actual markup of the template.

== Data Binding

Using a column template means you will not get any data binding between an editor control in the template and the data from a field in WebHierarchicalDataGrid; you must specify the column that an editor needs to bind to in order to display data from that column in the editor control.

== Related Topic

link:webhierarchicaldatagrid-using-item-template.html[Using Item Template]