////

|metadata|
{
    "name": "webhtmleditor-text-buttons-of-webhtmleditors-toolbar",
    "controlName": ["WebHtmlEditor"],
    "tags": ["Editing"],
    "guid": "{42370282-3C47-4078-8EFC-E49A4D0C6C74}",  
    "buildFlags": [],
    "createdOn": "2006-03-01T00:00:00Z"
}
|metadata|
////

= Text Buttons of WebHtmlEditor's Toolbar

Instances of the  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.toolbartext.html[ToolbarText]"]  class enable you as the developer to insert static text into the WebHtmlEditor™ toolbar. This allows you to customize the formatting and layout of items in the toolbar (through predefined  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.toolbartexttype.html[ToolbarTextTypes]"]  such as Tab and Break) or add information useful to your application's end users through ToolbarText objects of ToolbarTextType.Custom (for example, you can set the ToolbarText's  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.toolbartext~text.html[Text]"]  property to "Your upload directory is /uploads.")