////

|metadata|
{
    "name": "webhtmleditor-image-buttons-of-webhtmleditors-toolbar",
    "controlName": ["WebHtmlEditor"],
    "tags": ["Editing"],
    "guid": "{41293C0D-0845-4CBE-8215-C57766CD6693}",  
    "buildFlags": [],
    "createdOn": "2006-03-01T00:00:00Z"
}
|metadata|
////

= Image Buttons of WebHtmlEditor's Toolbar

Instances of the  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.toolbarimage.html[ToolbarImage]"]  class enable you as the developer to insert static images into the WebHtmlEditor™ toolbar. This allows you to customize the formatting and layout of items in the toolbar (through predefined ToolbarImageTypes such as Separator and RowSeparator) or insert icons conveying additional information useful to your application's end users through ToolbarImage objects of  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.toolbarimagetype.html[ToolbarImageType.Custom]"]  (for example, you could set the  pick:[asp-net="link:{ApiPlatform}webui.webhtmleditor{ApiVersion}~infragistics.webui.webhtmleditor.toolbarimage~imagename.html[ImageName]"]  property to a custom small LED light glowing green, amber or red, based on a status indicator within your application.)