////

|metadata|
{
    "name": "webimagebutton-csom-overview",
    "controlName": ["WebImageButton"],
    "tags": ["Localization","Styling"],
    "guid": "{7B9D1D51-9800-4AF0-93AB-C9D94BD356CB}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= CSOM Overview

WebImageButton™ exposes a robust object model within the client-side JavaScript programming environment. The client-side object model (CSOM) consists of full-fledged JavaScript objects, events, and utility functions that enable developers to program significant units of functionality pertaining to the WebImageButton control without the need for server-side postbacks.

In general, the object model is derived directly from the object model as it exists on the server. The property names, events, parameters and return values have very similar meanings to their counterparts on the server. However, where noted, properties are sometimes read-only on the client. These properties are only for informational purposes; you should not modify them.

The following are links to the CSOM reference information for the WebImageButton control:

link:webimagebutton-utility-functions-csom.html[WebImageButton Utility Functions]

link:webimagebutton-object-csom.html[WebImageButton Object]

____
link:webimagebutton-client-side-events-csom.html[Client-Side Events]
____