////

|metadata|
{
    "name": "webimagebutton-accessibility-compliance",
    "controlName": ["WebImageButton"],
    "tags": ["Layouts","Section 508","Styling"],
    "guid": "{5A21E1C0-F9A0-443D-84BE-55189AA2BD04}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebImageButton Accessibility Compliance

All of our ASP.NET controls and components comply with section 508, subpart 1194.22 of the Rehabilitation Act of 1973. Below is a table containing the specific rules of subpart 1194.22 that pertain to the control, and how we comply with each rule. In some cases, you may have to set a property. In other cases, you won't have to do anything as our control does all the work for you.

[options="header", cols="a,a"]
|====
|Rules|How We Comply with the Rules

|(a)
|By enabling the control's Section508Compliant property, all non-text elements render a text equivalent. 

.Note:
[NOTE]
====
A text equivalent is supplied by default, but this can be customized to suit your needs. 
====

|(c)
|By enabling the control's Section508Compliant property, you can supply an image (with alternate text) that will be used to convey the information.

|====