////

|metadata|
{
    "name": "webmaskeditor-data-modes-in-webmaskeditor",
    "controlName": ["WebMaskEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{A52BDD26-FBE2-40FA-B717-435BDD822A1B}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:06:34Z"
}
|metadata|
////

= Data Modes in WebMaskEditor

WebMaskEditor™ allows you to specify if input mask literals should be included with the value property. You can configure this behavior by simply setting the control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webmaskeditor~datamode.html[DataMode]"]  property This behavior can be configured according to the following variations:

* Whether or not the literal characters (non-editable part of mask such as slashes or dashes in date values) should be included.
* Whether or not the required empty mask positions should be included.
* Whether or not the optional empty mask positions should be included.

You can set the DataMode property to one of the members in the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.maskdatamode.html[MaskDataMode]"]  enumeration, either by using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebMaskEditor1.DataMode = Infragistics.Web.UI.EditorControls.MaskDataMode.RawTextWithLiterals
----

*In C#:*

----
WebMaskEditor1.DataMode = Infragistics.Web.UI.EditorControls.MaskDataMode.RawTextWithLiterals;
----