////

|metadata|
{
    "name": "webmaskeditor-display-modes-in-webmaskeditor",
    "controlName": ["WebMaskEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{9CF62C6C-B2A4-4A32-946C-9CEEBC2BA563}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:13:23Z"
}
|metadata|
////

= Display Modes in WebMaskEditor

WebMaskEditor™ provides you with two different options on how to display the text when control has no focus and no data. This option can be set by simply setting the control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webmaskeditor~displaymode.html[DisplayMode]"]  property.

You can set the DisplayMode property to one of the members in the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.maskdisplaymode.html[MaskDisplayMode]"]  enumeration, either by using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebMaskEditor1.DisplayMode = Infragistics.Web.UI.EditorControls.MaskDisplayMode.Mask
----

*In C#:*

----
WebMaskEditor1.DisplayMode = Infragistics.Web.UI.EditorControls.MaskDisplayMode.Mask;
----