////

|metadata|
{
    "name": "webnumericeditor-spinning-through-a-list-of-values-in-webnumericeditor",
    "controlName": ["WebNumericEditor"],
    "tags": [],
    "guid": "{2C27596A-3C7F-4445-AD18-5AEE144584E9}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T10:42:11Z"
}
|metadata|
////

= Spinning through a list of values in WebNumericEditor

WebNumericEditor™ provides the option to spin through a list of values using spin buttons. You can display the spin buttons by setting the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons~spinbuttonsdisplay.html[SpinButtonsDisplay]"]  property to either OnRight or OnLeft. By default, this property is set to None. The spin buttons have two buttons: lower and upper so that your end users can move to the next and previous values. You can customize the lower and upper buttons by setting the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons~lowerspinbutton.html[LowerSpinButton]"]  and  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons~upperspinbutton.html[UpperSpinButton]"]  properties respectively.

You can set the SpinButtonsDisplay property either using Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
'Displays the spin buttons on the right
WebNumericEditor1.Buttons.SpinButtonsDisplay = Infragistics.Web.UI.EditorControls.ButtonDisplay.OnRight
----

*In C#:*

----
//Displays the spin buttons on the right
WebNumericEditor1.Buttons.SpinButtonsDisplay = Infragistics.Web.UI.EditorControls.ButtonDisplay.OnRight;
----

WebNumericEditor also allows you to spin through the list continuously even if it reaches the first or last value in the list by setting the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons~spinwrap.html[SpinWrap]"]  property to True.

== Add and Insert Values into the list:

WebNumericEditor allows you to add a list of values that you want to iterate through using the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons.html[TextEditorButtons]"]  object's  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons~listofvalues.html[ListOfValues]"]  property. You can set the ListOfValues property either using Microsoft® Visual Studio® Property Window:

*In Visual Basic:*

----
WebNumericEditor1.Buttons.ListOfValues = "111|222|333|444|555"
----

*In C#:*

----
WebNumericEditor1.Buttons.ListOfValues = "111|222|333|444|555";
----

.Note:
[NOTE]
====
Items in the list must be separated by the "|" character when using the ListOfValues property.
====

However you can also insert values into the list using the TextEditorButtons object’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.texteditorbuttons~insertlistvalueatindex.html[InsertListValueAtIndex]"]  method.

*In Visual Basic:*

----
'Insert the values into the list at a particular index 
WebNumericEditor1.Buttons.InsertListValueAtIndex(0, "111")
WebNumericEditor1.Buttons.InsertListValueAtIndex(1, "222")
WebNumericEditor1.Buttons.InsertListValueAtIndex(2, "333")
WebNumericEditor1.Buttons.InsertListValueAtIndex(3, "444")
WebNumericEditor1.Buttons.InsertListValueAtIndex(4, "555")
----

*In C#:*

----
//Insert the values into the list at a particular index 
WebNumericEditor1.Buttons.InsertListValueAtIndex(0, "111");
WebNumericEditor1.Buttons.InsertListValueAtIndex(1, "222");
WebNumericEditor1.Buttons.InsertListValueAtIndex(2, "333");
WebNumericEditor1.Buttons.InsertListValueAtIndex(3, "444");
WebNumericEditor1.Buttons.InsertListValueAtIndex(4, "555");
----

== Increment/Decrement the editing value:

WebNumericEditor also allows you to increment/decrement the editing value using the spin buttons. You can set the increment/decrement factor by simply setting the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~spindelta.html[SpinDelta]"]  property. For instance, if you set the SpinDelta property to 10 then clicking the upper button increases the value by 10. Similarly clicking the lower button decreases the value by 10.

You can set the SpinDelta property either using Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebNumericEditor1.SpinDelta = 10
----

*In C#:*

----
WebNumericEditor1.SpinDelta = 10;
----

.Note:
[NOTE]
====
The ListOfValues property has higher priority than the SpinDelta property.
====