////

|metadata|
{
    "name": "webrating-accessibility-compliance",
    "controlName": ["WebRating"],
    "tags": ["Section 508","Selection"],
    "guid": "0fe99c67-76bb-4284-9529-e3dd618edc9e",  
    "buildFlags": [],
    "createdOn": "2010-06-01T04:46:53.8017535Z"
}
|metadata|
////

= WebRating Accessibility Compliance

All of our ASP.NET controls and components comply with section 508, subpart 1194.22 of the Rehabilitation Act of 1973. Below is a table containing the specific rules of subpart 1194.22 that pertain to the control, and how we comply with each rule. In some cases, you may have to set a property. In other cases, you won't have to do anything as our control does all the work for you.

[options="header", cols="a,a"]
|====
|Rules|How We Comply with the Rules

|(a)
|All IMG tags, which have key functionality, have "alt" attributes property set or allow for setting of the alt attribute value.

|(c)
|The control's markup is readable without requiring an associated style sheet because of the attributes described in rules A and B.

|(d)
|When the control's scripts are changing the page markup, the new created content comply with the screen reader due to the attributes described in rules A and C.

|(n)
|By using TAB key, you can navigate the control and its elements.

|====