////

|metadata|
{
    "name": "webschedule-data-model-for-the-resource-table",
    "controlName": ["WebSchedule"],
    "tags": ["Getting Started","Scheduling"],
    "guid": "{D6B9E523-478A-4CFF-9835-44182B173BF2}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Data Model for the Resource Table

The Resource table describes a WebSchedule™ Resource, which is any person, place, or thing, for which Activities may be scheduled. All columns correspond with .NET properties that have the same name on a Resource object, unless otherwise noted.

[options="header", cols="a,a,a,a"]
|====
|Column Name|Data Type|Null Allowed?|Remarks

|ResourceID
|int
|No
|*Primary Key.* A numeric value uniquely identifying this Resource.

|ResourceName
|nvarchar(64)
|No
|Name that uniquely identifies the resource it is meant to be a more user-friendly key.

|ResourceDescription
|ntext
|Yes
|Free-form text that describes this Resource.

|EmailAddress
|nvarchar(64)
|Yes
|Free-form text that contains the Resource's e-mail address.

|_ts
|timestamp
|Yes
|Timestamp that is used to detect concurrency conflicts.

|====

.Note:
[NOTE]
====
WebSchedule assumes the existence of an "Unassigned Resource". This data model avoids having null values in relationships between tables by requiring the presence of one row in the Resource table that must be pre-populated with a ResourceID of -999.
====