////

|metadata|
{
    "name": "webschedule-activities",
    "controlName": ["WebSchedule"],
    "tags": [],
    "guid": "{B213D664-CDDC-4B3C-BB4B-602B67B263C0}",  
    "buildFlags": [],
    "createdOn": "2005-01-08T00:00:00Z"
}
|metadata|
////

= Activities

Activities are fundamental to scheduling applications. WebSchedule™ models events occurring at a specific start date and time by instances of the abstract base class. An activity can be instantaneous or long-running (including all-day and multi-day events.)

The most common example of an Activity users interact with is the , which is an Activity having a subject, location and description. WebSchedule view elements present appointments differently. At right are examples of how the WebDayView™ and WebMonthView™ controls display the same day's schedule.

WebScheduleInfo contains the displayed activities in a collection that all attached views share, and works with a data provider to store and retrieve them from your data store.

* link:webschedule-add-an-activity-on-the-server.html[Add an Activity on the Server]
* link:webschedule-add-an-activity-to-the-database.html[Add an Activity to the Database]
* link:webschedule-adding-an-activity-on-the-client-side.html[Adding an Activity on the Client Side]
* link:webschedule-create-an-activity-using-code.html[Create an Activity Using Code]
* link:webschedule-deleting-an-activity-on-the-client-side.html[Deleting an Activity on the Client Side]
* link:webschedule-limiting-appointment-dates-and-times.html[Limiting Appointment Dates and Times]
* link:webschedule-locate-an-activity.html[Locate an Activity]
* link:webschedulegenericdataprovider-multi-day-event-banner.html[Multi Day Event Banner]
* link:webschedule-remove-an-activity-from-the-database.html[Remove an Activity from the Database]
* link:webschedule-remove-an-activity-on-the-server.html[Remove an Activity on the Server]
* link:webschedule-updating-an-activity-on-the-client-side.html[Updating an Activity on the Client Side]
* link:webschedule-working-with-resources-and-activities.html[Working with Resources and Activities]