////

|metadata|
{
    "name": "webschedule-resources",
    "controlName": ["WebSchedule"],
    "tags": [],
    "guid": "{E6946FEC-601C-4CFA-857A-36B626EC4324}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Resources

link:infragistics4.webui.webschedule.v{ProductVersion}~infragistics.webui.webschedule.resource.html[Resources]  are people or things having  link:infragistics4.webui.webschedule.v{ProductVersion}~infragistics.webui.webschedule.activity.html[activities]  that are managed by your scheduling application. Examples include employees in a factory, or conference rooms in an office.

In WebSchedule™, activities can be displayed for one active resource at a time. This resource is also called the link:infragistics4.webui.webschedule.v{ProductVersion}~infragistics.webui.webschedule.webscheduleinfo~visibleresources.html[VisibleResources] .

End users viewing your WebSchedule application do not need to be resources, but when they are they can receive reminder notifications for their activities as described in the link:webschedule-reminders.html[Reminders] topic.

* link:webschedule-multi-resource-view.html[Multi Resource View]
* link:webschedule-unassigned-resource.html[Unassigned Resource]
* link:webschedule-creating-a-logon-dialog-box-for-your-webschedule-application.html[Creating a Logon Dialog Box for Your WebSchedule Application]
* link:webschedule-extending-appointments-and-resources.html[Extending Appointments and Resources]
* link:webschedule-setting-the-time-zone.html[Setting the Time Zone]

