////

|metadata|
{
    "name": "webtexteditor-using-webtexteditor-in-multiline-mode",
    "controlName": ["WebTextEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{A85A6006-E431-4E01-AB95-93A2BC8B21AA}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T09:45:42Z"
}
|metadata|
////

= Using WebTextEditor in MultiLine mode

WebTextEditor™ can easily be configured for multiline mode where you can specif the number of lines and characters per line to be displayed by setting the  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.multiline.html[MultiLine]"]  object’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.multiline~rows.html[Rows]"]  and  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.multiline~columns.html[Columns]"]  properties. You can also set the MultiLine object’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.multiline~wrap.html[Wrap]"]  and  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.multiline~overflow.html[Overflow]"]  properties to wrap the text in the text area and control the overflow style respectively.

To use WebTextEditor in multiline mode you must set the control’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webtexteditor~textmode.html[TextMode]"]  property to MultiLine. You can set the TextMode property to MultiLine either by using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebTextEditor1.TextMode = TextBoxMode.MultiLine
----

*In C#:*

----
WebTextEditor1.TextMode = TextBoxMode.MultiLine;
----