////

|metadata|
{
    "name": "webtab-validation-in-webtab",
    "controlName": ["WebTab"],
    "tags": ["How Do I"],
    "guid": "{80286CE8-658D-47F3-80E3-B95BD4081AE9}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Validation in WebTab

WebTab™ supports validation of ASP validators in the selected tab by default. When the content pane has validators then before changing the selected tab or reloading the tab, the validators are checked. If the validation fails, then the selected tab does not change or reload. This feature can be disabled by setting the control’s  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.webtab~enablevalidation.html[EnableValidation]"]  property to False.

*In HTML:*

----
<ig:WebTab ID="WebTab1" runat="server" Height="367px" 
             Width="863px" EnableValidation=" >
            <Tabs>
                …
            </Tabs>
</ig:WebTab>
----

*In Visual Basic:*

----
WebTab1.EnableValidation = false
----

*In C#:*

----
WebTab1.EnableValidation = false;
----

.Note:
[NOTE]
====
This feature validates child controls located in the template of the tab item and for  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.contentpane~contenturl.html[ContentUrl]"]  as well (only if ContentUrl points to a local aspx page).
====

== Related Topics

link:webtab-about-webtab.html[Understanding WebTab]

link:webtab-getting-started-with-webtab.html[Getting Started with WebTab]

link:webtab-header-and-content-panes.html[Header and Content Panes]

link:webtab-tab-states.html[Tab States]

link:webtab-ajax-indicator-support-for-webtab.html[Ajax Indicator Support for WebTab]

link:webtab-display-modes.html[Display Modes]

link:webtab-animations.html[Animations]

link:webtab-handling-overflow-in-webtab.html[Handling Overflow in WebTab]

link:webtab-load-on-demand.html[Load on Demand]

link:webtab-orientation-and-alignment.html[Orientation and Alignment]

link:webtab-overlapping-tabs.html[Overlapping Tabs]

link:webtab-tab-moving.html[Tab Moving]

link:webtab-scrolling.html[Scrolling]

link:webtab-api-overview.html[API Overview]

link:webtab-client-side-object-model.html[Client-Side Object Model(CSOM) Overview]