////

|metadata|
{
    "name": "webtexteditor-using-webtexteditor-in-password-mode",
    "controlName": ["WebTextEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{D2EE15D9-0104-496D-8CFA-6627A7E7C7D3}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T09:39:24Z"
}
|metadata|
////

= Using WebTextEditor in password mode

WebTextEditor™ can easily be set to password mode so that other people standing by will not be able to see what your end user is typing into the editor.

.Note:
[NOTE]
====
The text entered into the WebTextEditor in password mode is not encrypted in any way and you should protect it as you would any other confidential data.
====

To use WebTextEditor in password mode you must set the control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.editorcontrols.webtexteditor~textmode.html[TextMode]"]  property to Password. You can set the TextMode property to Password either by using the Microsoft® Visual Studio® Property Window or by using the following code:

*In Visual Basic:*

----
WebTextEditor1.TextMode = TextBoxMode.Password
----

*In C#:*

----
WebTextEditor1.TextMode = TextBoxMode.Password;
----