////

|metadata|
{
    "name": "webtab-overlapping-tabs",
    "controlName": ["WebTab"],
    "tags": ["How Do I"],
    "guid": "{BE800D6E-F910-4542-882B-44F06D552E52}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= Overlapping Tabs

WebTab™ provides you with an overlapping feature, which allows you to show each tab overlapping with its adjacent tabs. By default, overlapping of tabs is disabled. However you can enable this feature by setting the control’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.webtab~enableoverlappingtabs.html[EnableOverlappingTabs]"]  property to True. You can also customize the Css classes with respect to this feature by assigning your own Css class to the  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.webtab~cssclasses.html[CssClasses]"]  object’s  pick:[asp-net="link:infragistics4.web.v{ProductVersion}~infragistics.web.ui.layoutcontrols.tabcssclasses~overlappingtabscssclass.html[OverlappingTabsCssClass]"]  property. The applied class is merged with the igtab_XXOverlap Css.

*In HTML:*

----
<ig:WebTab ID="WebTab1" runat="server" EnableOverlappingTabs="True" 
        Height="200px" Width="300px">
        <Tabs>
        …
        </Tabs>
         <CssClasses OverlappingTabsCssClass="overlap" />
</ig:WebTab>
----

*In Visual Basic:*

----
WebTab1.EnableOverlappingTabs = True
'Assuming overlap as your Css class
WebTab1.CssClasses.OverlappingTabsCssClass = "overlap"
----

*In C#:*

----
WebTab1.EnableOverlappingTabs = true;
//Assuming overlap as your Css class
WebTab1.CssClasses.OverlappingTabsCssClass = "overlap";
----

.Note:
[NOTE]
====
If EnableOverlappingTabs is enabled, then OverlappingTabsCssClass is applied to all tab items besides the first one. This class only defines the location where the tabs should be shifted, but does not affect the appearance of the tab item.
====

== Related Topics

link:webtab-about-webtab.html[Understanding WebTab]

link:webtab-getting-started-with-webtab.html[Getting Started with WebTab]

link:webtab-header-and-content-panes.html[Header and Content Panes]

link:webtab-tab-states.html[Tab States]

link:webtab-ajax-indicator-support-for-webtab.html[Ajax Indicator Support for WebTab]

link:webtab-display-modes.html[Display Modes]

link:webtab-animations.html[Animations]

link:webtab-handling-overflow-in-webtab.html[Handling Overflow in WebTab]

link:webtab-load-on-demand.html[Load on Demand]

link:webtab-orientation-and-alignment.html[Orientation and Alignment]

link:webtab-tab-moving.html[Tab Moving]

link:webtab-scrolling.html[Scrolling]

link:webtab-validation-in-webtab.html[Validation in WebTab]

link:webtab-api-overview.html[API Overview]

link:webtab-client-side-object-model.html[Client-Side Object Model(CSOM) Overview]