////

|metadata|
{
    "name": "whats-new-in-2014-volume-2",
    "controlName": [],
    "tags": ["Charting","CTP","Data Binding","Data Presentation","Design Environment"],
    "guid": "ec056f5c-07bd-4a71-8b5b-48ffa84cc3a1",  
    "buildFlags": [],
    "createdOn": "2014-09-16T12:26:19.2522493Z"
}
|metadata|
////

= What's New in 2014 Volume 2

== Topic Overview

=== Purpose

This topic provides an overview of the new things and new and enhanced features for the Infragistics® ASP.NET 2014 Volume 2 release.

== What’s New Summary

=== What’s new summary chart

The following table summarizes what’s new in 2014 Volume 2 release. Additional details follow the summary table.

==== <<_Ref367305754,General>>

[options="header", cols="a,a"]
|====
|Feature|Description

|<<wrapper-igniteui,ASP.NET Web Forms Wrappers for Ignite UI Data Chart>>
|The WebDataChart is a component based on Ignite UI Data Chart and ASP.NET Web Forms Server Control. The component can be easily configured and previewed in Design view of the Visual Studio.

|====

[[_Ref367305754]]

== General

[[wrapper-igniteui]]

=== ASP.NET Web Forms Wrappers for Ignite UI Data Chart

The WebDataChart is a component based on Ignite UI Data Chart and ASP.NET Web Forms Server Control. The component can be easily configured and previewed in Design view of the Visual Studio. Following features are included in the data chart preview:

* Changing and resizing data chart height and width
* Binding a data chart to different data sources (axes and series are generated based on that data source schema)
* Customize axes and series of a data chart

This component includes limited features and it’s available as separate installer.